using System.Collections.Generic;
using System.Globalization;

namespace TweakFirmware.Core.Localization
{
    /// <summary>
    /// Единое хранилище всех текстов интерфейса, диалогов и журнала — на русском и
    /// английском. Не .resx: строгая типизация через автогенерируемый Designer.cs
    /// требует специфичной MSBuild-конфигурации (Generator=MSBuild:Compile +
    /// StronglyTyped*-метаданные), у которой давняя история проблем в разных версиях
    /// .NET SDK при сборке без Visual Studio (именно так собирается релиз в CI —
    /// обычным "dotnet publish"). Обычный класс со словарями даёт тот же результат
    /// (тексты не смешаны с разметкой/кодом, один файл на язык, легко добавить
    /// третий язык) без риска, что сборка сломается на билд-сервере.
    ///
    /// Язык переключается через <see cref="SetLanguage"/> — его вызывает
    /// TweakFirmware.Services.LocalizationService (главное приложение) при старте
    /// и при выборе языка в настройках. Здесь же — общий формат размеров
    /// (SizeFormatHelper) и сообщения ядра (FileSplitter/FileMerger/HashHelper),
    /// поэтому файл лежит в Core, а не в основном проекте.
    /// </summary>
    public static class Strings
    {
        public const string DefaultLanguage = "ru";

        public static string CurrentLanguage { get; private set; } = DefaultLanguage;

        public static void SetLanguage(string code)
        {
            CurrentLanguage = code == "en" ? "en" : "ru";
        }

        public static string Get(string key)
        {
            var table = CurrentLanguage == "en" ? En : Ru;
            return table.TryGetValue(key, out var value) ? value : (Ru.TryGetValue(key, out var fallback) ? fallback : key);
        }

        /// <summary>string.Format с текущей культурой отображения (влияет на разделители чисел).</summary>
        public static string Format(string key, params object[] args) =>
            string.Format(CultureInfo.CurrentCulture, Get(key), args);

        private static readonly Dictionary<string, string> Ru = new()
        {
            // ===================== Общее =====================
            ["Common_Error"] = "Ошибка",
            ["Common_ErrorLog"] = "Ошибка: {0}",
            ["Common_PauseButton"] = "Приостановить",
            ["Common_ResumeButton"] = "Возобновить",
            ["Common_FileNotFoundTitle"] = "Файл не найден",
            ["Common_FileNotFoundMessage"] = "По указанному пути файла нет:\n{0}",
            ["Common_BrowseButton"] = "📁 Обзор…",
            ["Common_AllFilesFilter"] = "Все файлы (*.*)|*.*",
            ["Common_TextFileFilter"] = "Текстовый файл (*.txt)|*.txt",
            ["Common_BinFileFilter"] = "BIN файлы (*.bin)|*.bin|Все файлы (*.*)|*.*",
            ["Common_LogOpenButton"] = "Открыть",
            ["Common_LogSaveButton"] = "Сохранить",
            ["Common_LogClearButton"] = "Очистить",
            ["Common_LogCopyButton"] = "Копировать",
            ["Common_LogResizeTooltip"] = "Потяните, чтобы изменить высоту журнала",
            ["Common_CopyHashTooltip"] = "Скопировать хэш",
            ["Common_CopiedTooltip"] = "Скопировано",
            // Подписи хэшей в окнах с итогом. Раньше хэши были вписаны прямо в текст
            // сообщения, и скопировать их было нельзя — только перепечатать.
            ["Common_HashConfirmedLabel"] = "SHA-256 подтверждён:",
            ["Common_LogTitle"] = "Журнал",
            ["Common_ProgressTitle"] = "Прогресс",
            ["Common_OpenFolderCheckbox"] = "Открыть папку с результатом",
            ["Common_SaveLogFailed"] = "Не удалось сохранить лог:\n{0}",
            ["Common_FileProgressLabel"] = "{0} — файл {1} из {2}",
            ["Common_OverwriteChoice"] = "Перезаписать",
            ["Common_CancelChoice"] = "Отмена",
            ["Common_DigitsOnly"] = "Разрешены только цифры",
            ["Common_DestinationFolderLabel"] = "Папка назначения",
            // С упоминанием перетаскивания: сама возможность есть с самого начала,
            // но подсказки о ней не было нигде — и о ней просто не догадывались.
            ["Common_NoFileSelected"] = "Файл не выбран — можно перетащить сюда",
            ["Common_NoFolderSelected"] = "Папка не выбрана — можно перетащить сюда",
            ["Common_SelectFileHint"] = "Выберите необходимый файл для начала работы.",
            ["Common_CancelButton"] = "Отмена",
            ["Common_OkButton"] = "ОК",
            ["Common_CannotStartTitle"] = "Нельзя начать",
            ["Common_LowSpaceTitle"] = "Недостаточно места",
            ["Common_DoneTitle"] = "Готово",
            ["Common_VerifyErrorTitle"] = "Ошибка проверки",
            ["Common_CancelledTitle"] = "Отменено",
            ["Common_DeletingIncompleteLog"] = "Удаление незавершённых файлов ({0})...",
            ["Common_DeletedLog"] = "Удалён: {0}",
            ["Common_DeleteFailedLog"] = "Не удалось удалить {0}: {1}",
            ["Common_ClipboardFailedLog"] = "Не удалось записать в буфер обмена ({0}).",
            ["Common_UnexpectedErrorTitle"] = "Непредвиденная ошибка",
            ["Common_UnexpectedErrorMessage"] = "Произошло то, чего программа не предусмотрела:\n{0}\n\nРабота продолжена, но результат этого действия может быть неполным. Подробности записаны в журнал.",
            ["Common_UnexpectedErrorLog"] = "Непредвиденная ошибка ({0}): {1} — {2}",
            ["Common_OutputNotUsableMessage"] = "С этим местом сохранения работать не получается:\n{0}\n\nПроверьте путь: диск должен существовать и быть доступен для записи. У сетевых папок программа не всегда может узнать свободное место — тогда снимите галочку «Проверить свободное место на диске».",
            ["Common_GeneralInfoTitle"] = "Общая информация",
            ["Common_ParametersTitle"] = "Параметры",
            ["Common_CheckDiskSpaceCheckbox"] = "Проверить свободное место на диске",
            ["Common_CurrentFileProgressLabel"] = "Текущий файл",
            ["Common_OpenFolderFailedLog"] = "Не удалось открыть папку: {0}",
            ["Update_GitHubRespondedError"] = "GitHub ответил: {0} {1}",
            ["Update_CheckFailedError"] = "Не удалось проверить обновления: {0}",

            // ===================== Размеры (SizeFormatHelper) =====================
            ["Size_GbFormat"] = "{0:F2} ГБ ({1:N0} байт)",
            ["Size_MbFormat"] = "{0:F2} МБ ({1:N0} байт)",

            // ===================== Ядро: исключения и журнал =====================
            ["Core_SourceFileNotFound"] = "Исходный файл не найден",
            ["Core_ChainBaseFileNotFound"] = "Базовый файл цепочки не найден",
            ["Core_ChainPartMissing"] = "В цепочке нет части {0}, но есть часть {1}: собирать нечего — файл получился бы неполным.",
            ["Core_CannotDetermineDrive"] = "Не удалось определить диск для пути: {0}",
            ["Log_Created"] = "Лог создан",
            ["Log_Cleared"] = "Лог очищен",
            ["Log_TrimmedOlderEntries"] = "— старые записи ({0}) удалены, чтобы журнал не разрастался —",
            ["Log_AppStarted"] = "Приложение запущено",
            ["Log_TimestampLabel"] = "Дата и время",
            ["Log_PartCreated"] = "Создан {0} (файл {1} из {2})",
            ["Log_PartFilled"] = "Файл {0} заполнен ({1:N0} байт)",
            ["Log_PartFinished"] = "Файл {0} завершён ({1:N0} байт)",
            ["Log_ClosingFile"] = "Дописываю на диск {0}... (может занять время: файл большой)",
            ["Log_VerifyingHash"] = "Проверка SHA-256: повторное чтение всех частей подряд...",
            ["Log_HashMatches"] = "SHA-256 совпадает — байты не потеряны",
            ["Log_HashMismatchError"] = "Ошибка: SHA-256 не совпадает — проверьте результат.",
            ["Log_ChainFound"] = "Найдено частей в цепочке: {0} (всего {1:N0} байт)",
            ["Log_ReadingPart"] = "Читаю {0} (файл {1} из {2})",
            ["Log_MergeFinished"] = "Сборка завершена: {0} ({1:N0} байт)",

            // ===================== Оболочка/навигация/автообновление =====================
            ["Shell_NavConvert"] = "Конвертирование",
            ["Shell_NavMerge"] = "Сборка файла",
            ["Shell_NavVerify"] = "Проверка SHA-256",
            ["Shell_NavExtract"] = "Извлечение разделов",
            ["Shell_NavPartitionMerge"] = "Объединение разделов",
            ["Shell_NavSettings"] = "Настройки",
            ["Shell_NavAbout"] = "О программе",
            ["Shell_FilesGroupHeader"] = "РАБОТА С ФАЙЛАМИ",
            ["Shell_PartitionsGroupHeader"] = "РАБОТА С РАЗДЕЛАМИ",
            ["Shell_MiscGroupHeader"] = "РАЗНОЕ",
            ["Shell_SystemGroupHeader"] = "СИСТЕМА",
            ["Shell_WindowTitle"] = "Tweak Firmware",
            ["Shell_TitleBarTitle"] = "Tweak Firmware",
            ["Shell_MenuToggleTooltip"] = "Показать или скрыть меню",
            ["Shell_UpdateBanner"] = "Доступна новая версия {0}",
            ["Shell_UpdateDownloadButton"] = "Скачать",
            ["Shell_UpdateInstallButton"] = "Установить и перезапустить",
            ["Shell_UpdateReadyBanner"] = "Версия {0} загружена и готова к установке",
            ["Shell_UpdateWaitingForOperation"] = "Установка будет доступна после завершения операции",
            ["Shell_UpdateDownloadCancelledLog"] = "Загрузка обновления отменена",
            ["Shell_UpdateInstallerMissingMessage"] = "Скачанный установщик не найден — попробуйте скачать обновление заново.",
            ["Shell_LaterButton"] = "Позже",
            ["Shell_DownloadingUpdate"] = "Загрузка обновления... {0:F0}%",
            ["Shell_Installing"] = "Установка...",
            ["Shell_UpdateErrorTitle"] = "Ошибка обновления",
            ["Shell_UpdateErrorMessage"] = "Не удалось скачать или установить обновление:\n{0}",
            ["Shell_UpdateFoundLog"] = "Найдено обновление: версия {0} (текущая {1})",
            ["Shell_UpdateDownloadStartLog"] = "Начата загрузка обновления {0}: {1}",
            ["Shell_UpdateDownloadedLog"] = "Обновление скачано и готово к установке",
            ["Shell_UpdateErrorLog"] = "Ошибка автообновления: {0}",
            ["Shell_Placeholder_InDevelopment"] = "В разработке",

            // ===================== Конвертирование =====================
            ["Convert_Title"] = "Конвертирование",
            ["Convert_SourceFileLabel"] = "Исходный файл .bin",
            ["Convert_ProgrammerModelLabel"] = "Модель программатора",
            ["Convert_LimitLabel"] = "Лимит на один файл",
            ["Convert_LimitPlaceholder"] = "Указывается в байтах",
            ["Convert_SourceInsideOutputMessage"] = "Исходный файл лежит там же, куда программа собирается писать, и один из создаваемых файлов лёг бы прямо на него.\n\nВыберите другую папку назначения или другое имя файлов.",
            ["Convert_VerifyHashCheckbox"] = "Проверить SHA-256",
            ["Convert_OverallProgressLabel"] = "Конвертирование",
            ["Convert_HashProgressLabel"] = "Алгоритм SHA-256",
            ["Convert_StartButton"] = "Начать",
            ["Convert_CustomPresetName"] = "Пользовательские настройки",
            ["Convert_ChooseOutputFolderTitle"] = "Выберите папку вывода",
            ["Convert_ShowAllFilesButton"] = "Показать все файлы",
            ["Convert_SourceSizeLine"] = "Размер исходного файла: {0}",
            ["Convert_ExpectedCountLine"] = "Ожидаемое количество файлов: {0}",
            ["Convert_InvalidLimitLine"] = "Укажите размер части не меньше 1024 байт",
            ["Convert_TooManyFilesLine"] = "Файлов слишком много, чтобы показать список",
            ["Convert_EachFileSizeHeader"] = "Размер каждого файла:",
            ["Convert_FileSizeLine"] = "Файл {0}: {1}",
            ["Convert_MoreFilesLine"] = "… и ещё {0} файл(ов)",
            ["Convert_CollapseList"] = "Свернуть список",
            ["Convert_ShowAllFilesCount"] = "Показать все {0} файлов",
            ["Convert_SelectSourceFirst"] = "Выберите существующий исходный файл.",
            ["Convert_SpecifyOutputFolder"] = "Укажите папку вывода.",
            ["Convert_InvalidPartSize"] = "Некорректный размер части.",
            ["Convert_ConflictTitle"] = "Файлы уже существуют",
            ["Convert_ConflictMessage"] = "В папке уже есть файлы с именем «{0}» (или его частей).",
            ["Convert_NewFolderNearby"] = "Новая папка",
            ["Convert_ConflictLog"] = "Обнаружен конфликт имён — используется новая папка: {0}",
            ["Convert_LowSpaceMessage"] = "Размер исходного файла: {0}\nНеобходимо (с запасом 5%): {1}\nСвободно: {2}\nНе хватает: {3}",
            ["Convert_StartLog"] = "Начало конвертирования: {0} -> {1}\\{2} (макс. {3:N0} байт/файл)",
            ["Convert_FinishedLog"] = "Конвертирование завершено. Файлов: {0}, всего байт: {1:N0}",
            ["Convert_DoneVerifiedMessage"] = "Конвертирование завершено успешно.\n\nСоздано файлов: {0}",
            ["Convert_VerifyErrorMessage"] = "Контрольные суммы не совпадают — данные повреждены.",
            ["Convert_HashSourceLabel"] = "Исходный файл:",
            ["Convert_HashResultLabel"] = "Созданные части:",
            ["Convert_DoneMessage"] = "Конвертирование завершено.\n\nСоздано файлов: {0}",
            ["Convert_CancelledLog"] = "Конвертирование отменено пользователем",
            ["Convert_CancelledMessage"] = "Конвертирование отменено.\nУдалено незавершённых файлов: {0}",
            ["Convert_DiskFullMessage"] = "На диске закончилось свободное место во время записи.\n\nОперация прервана, незавершённые файлы ({0}) удалены — освободите место и попробуйте снова.",
            ["Convert_ErrorMessage"] = "Не удалось завершить конвертирование:\n{0}\n\nНезавершённые файлы ({1}) удалены.",
            ["Convert_ResumedLog"] = "Операция возобновлена пользователем",
            ["Convert_PausedLog"] = "Операция приостановлена пользователем",

            // ===================== Сборка файла =====================
            ["Merge_Title"] = "Сборка файла",
            ["Merge_SourceFileFilter"] = "BIN и части (*.bin;*.part*)|*.bin;*.bin.part*|Все файлы (*.*)|*.*",
            ["Merge_AnyChainPartLabel"] = "Любая часть цепочки",
            ["Merge_ExpectedHashLabel"] = "Ожидаемый SHA-256",
            ["Merge_ExpectedHashTooltip"] = "Если известен хэш оригинального файла — вставьте сюда для сверки",
            ["Merge_ExpectedHashPlaceholder"] = "Необязательно — вставьте, если известен",
            ["Merge_OutputInsideChainMessage"] = "Файл результата — это один из файлов собираемой цепочки, и сборка уничтожила бы его: он обнуляется до того, как его успеют прочитать.\n\nУкажите другое имя или другую папку для результата.",
            ["Merge_ExpectedHashHint"] = "Это не похоже на SHA-256: нужно {0} символов из цифр и букв A–F",
            ["Merge_ExpectedHashInvalidMessage"] = "Поле «Ожидаемый SHA-256» заполнено, но это не хэш.\n\nSHA-256 — это ровно {0} символов из цифр и букв A–F. Проверьте, что строка скопирована полностью, либо очистите поле — тогда сборка пройдёт без сверки.",
            ["Merge_ResultSizeLine"] = "Размер итогового файла: {0}",
            ["Merge_OverallProgressLabel"] = "Сборка",
            ["Merge_StartButton"] = "Начать",
            ["Merge_ChainFoundInfo"] = "Найдено частей: {0} ({1}). Первая: {2}",
            ["Merge_ChainNamingHint"] = "Части ищутся по именам: emmc.bin, emmc.bin.part1, emmc.bin.part2 и далее по порядку.",
            ["Merge_UnevenPartsWarning"] = "Части цепочки разного размера — выбивается часть {0}. Так бывает, если цепочку резала другая программа; если эта — часть могла скопироваться не полностью. Результат стоит сверить по SHA-256.",
            ["Merge_ChainResolveError"] = "Не удалось определить цепочку: {0}",
            ["Merge_SelectSourceFirst"] = "Выберите файл из цепочки частей.",
            ["Merge_SpecifyOutputFile"] = "Укажите файл результата.",
            ["Merge_FileExistsTitle"] = "Файл уже существует",
            ["Merge_FileExistsMessage"] = "Файл «{0}» уже существует.",
            ["Merge_NewNameNearby"] = "Новое имя",
            ["Merge_ConflictLog"] = "Обнаружен конфликт имени — используется новый файл: {0}",
            ["Merge_ChainCheckErrorMessage"] = "Не удалось проверить цепочку частей:\n{0}",
            ["Merge_LowSpaceMessage"] = "Размер собираемых данных: {0}\nНеобходимо (с запасом 5%): {1}\nСвободно: {2}\nНе хватает: {3}",
            ["Merge_StartLog"] = "Начало сборки: {0} -> {1}",
            ["Merge_FinishedLog"] = "Сборка завершена. Частей: {0}, байт: {1:N0}",
            ["Merge_ResultHashLog"] = "SHA-256 результата: {0}",
            ["Merge_HashMatchLog"] = "Сверка с указанным хэшем: совпадает ✓",
            ["Merge_HashMismatchLog"] = "Сверка с указанным хэшем: не совпадает!",
            ["Merge_ResultMatchMessage"] = "Сборка завершена.\n\nSHA-256 совпадает с указанным.",
            ["Merge_ResultMismatchMessage"] = "SHA-256 не совпадает с ожидаемым.",
            ["Merge_HashExpectedLabel"] = "Ожидался:",
            ["Merge_HashActualLabel"] = "Получен:",
            ["Merge_DoneMessage"] = "Сборка завершена.\n\nЧастей: {0}\nРазмер: {1:N0} байт",
            ["Merge_HashResultLabel"] = "SHA-256 собранного файла:",
            ["Merge_CancelledLog"] = "Сборка отменена пользователем",
            ["Merge_CancelledMessage"] = "Сборка отменена.\nНезавершённый файл результата удалён.",
            ["Merge_DiskFullMessage"] = "На диске закончилось свободное место во время записи.\n\nОперация прервана, незавершённый файл результата удалён — освободите место и попробуйте снова.",
            ["Merge_ErrorMessage"] = "Не удалось завершить сборку:\n{0}\n\nНезавершённый файл результата удалён.",
            ["Merge_ResumedLog"] = "Операция возобновлена пользователем",
            ["Merge_PausedLog"] = "Операция приостановлена пользователем",

            // ===================== Проверка SHA-256 =====================
            ["Verify_Title"] = "Проверка SHA-256",
            ["Verify_FileLabel"] = "Файл {0}",
            ["Verify_AddFileButton"] = "Добавить файл",
            ["Verify_RemoveFileTooltip"] = "Убрать этот файл",
            ["Verify_MaxFilesNote"] = "Максимум: {0} файлов",
            ["Verify_SelectFilesHint"] = "Выберите необходимые файлы для начала работы.",
            ["Verify_FilesSelectedLine"] = "Выбрано файлов: {0}",
            ["Verify_InfoFileLine"] = "{0} — {1}",
            ["Verify_InfoFileMissingLine"] = "{0} — файл не найден",
            ["Verify_SizesDifferNote"] = "Размеры файлов различаются — одинаковыми их хэши быть уже не могут.",
            ["Verify_CompareProgressLabel"] = "Сравнение",
            ["Verify_CompareButton"] = "Начать",
            ["Verify_SelectBothFiles"] = "Выберите файлы для сравнения — нужно минимум два.",
            ["Verify_FilesMissingMessage"] = "Не найдены файлы:\n{0}",
            ["Verify_CompareLog"] = "Сравнение хэшей: файлов {0}",
            ["Verify_FileLabelProgress"] = "Файл {0} из {1} — {2}",
            ["Verify_HashesMatchLog"] = "Хэши совпадают",
            ["Verify_HashesMismatchLog"] = "Хэши не совпадают",
            ["Verify_ResultTitle"] = "Результат",
            ["Verify_NoResultYet"] = "Сравнение ещё не выполнялось",
            ["Verify_CancelledMessage"] = "Сравнение отменено — хэши посчитаны не для всех файлов.",
            ["Verify_AllIdenticalHeadline"] = "Все файлы идентичны",
            ["Verify_AllIdenticalSubline"] = "Проверено: {0} файлов — у всех один и тот же SHA-256.",
            ["Verify_DifferenceHeadline"] = "Обнаружено различие",
            ["Verify_DifferenceSubline"] = "{0} из {1} файлов идентичны.",
            ["Verify_AllDifferentSubline"] = "Все {0} файлов различаются между собой.",
            ["Verify_GroupTitle"] = "SHA-256 группы {0} — файлов: {1}",
            ["Verify_SingleGroupTitle"] = "SHA-256",
            ["Verify_HashErrorMessage"] = "Не удалось вычислить хэш:\n{0}",

            // ===================== Настройки =====================
            ["Settings_Title"] = "Настройки",
            ["Settings_ThemeTitle"] = "Тема оформления",
            ["Settings_ThemeLight"] = "Светлая",
            ["Settings_ThemeDark"] = "Тёмная",
            ["Settings_ThemeSystem"] = "Как в системе",
            ["Settings_LanguageTitle"] = "Язык интерфейса",
            ["Settings_LanguageRu"] = "Русский",
            ["Settings_LanguageEn"] = "English",
            ["Settings_UseDefaultPathCheckbox"] = "Путь по умолчанию",
            ["Settings_ChooseConvertFolderTitle"] = "Папка по умолчанию для конвертирования",
            ["Settings_ChooseMergeFolderTitle"] = "Папка по умолчанию для сборки файла",
            ["Settings_ChooseExtractFolderTitle"] = "Папка по умолчанию для извлечения разделов",
            ["Settings_ConvertFolderTitle"] = "Папка для конвертирования",
            ["Settings_MergeFolderTitle"] = "Папка для сборки файла",
            ["Settings_ExtractFolderTitle"] = "Папка для извлечения разделов",
            // Раньше карточка называлась «Очистить кеш» и обещала удалить временные файлы.
            // Никаких временных файлов программа не создаёт — чистится только журнал,
            // поэтому и название, и описание теперь про него.
            ["Settings_ClearLogTitle"] = "Журнал приложения",
            ["Settings_ClearLogDescription"] = "Удаляет все записи журнала — и в карточке «Журнал» на рабочих вкладках, и в файле на диске.",
            ["Settings_ClearLogButton"] = "Очистить журнал",
            ["Settings_LogClearedMessage"] = "Журнал очищен.",

            // ===================== О программе =====================
            ["About_Title"] = "О программе",
            ["About_TaglineText"] = "Программа для работы с прошивками: конвертирование и сборка дампов, извлечение и объединение разделов, проверка хэш-сумм.",
            ["About_UpdatesTitle"] = "Обновления",
            ["About_UpdatesDescription"] = "Проверяйте наличие новых версий программы.",
            ["About_CheckUpdatesButton"] = "Проверить обновления",
            ["About_Checking"] = "Проверка...",
            ["About_UpdateAvailable"] = "Доступна новая версия: {0} (см. уведомление сверху)",
            ["About_UpToDate"] = "У вас последняя версия.",
            ["About_CheckUpdatesTitle"] = "Проверка обновлений",
            ["About_DevelopmentTitle"] = "Разработка",
            ["About_DevelopmentText"] = "Alxmak и несколько чат-ботов.",
            ["About_PersonalUseText"] = "Программа создавалась для использования в личных целях.",
            ["About_SourcesTitle"] = "Источники информации",
            ["About_SourcesDescription"] = "Форумы и сайты, материалы которых помогли в работе над программой.",
            ["About_VersionText"] = "Версия {0}",

            // ===================== Обратная связь =====================
            ["Feedback_Title"] = "Обратная связь",
            ["Feedback_Intro"] = "Буду благодарен за ваши отзывы, предложения и сообщения об ошибках.",
            ["Feedback_WriteButton"] = "Написать письмо",
            ["Feedback_CopyAddressButton"] = "Скопировать адрес",
            ["Feedback_AddressCopiedButton"] = "Адрес скопирован",
            ["Feedback_CopyFailedStatus"] = "Не удалось скопировать: буфером обмена занято другое приложение, попробуйте ещё раз.",
            ["Feedback_NoMailClientCopied"] = "Не удалось открыть почтовый клиент — похоже, он не назначен в системе. Адрес {0} скопирован в буфер обмена, напишите, пожалуйста, вручную.",
            ["Feedback_NoMailClient"] = "Не удалось открыть почтовый клиент — похоже, он не назначен в системе. Напишите, пожалуйста, вручную на {0}.",
            ["Feedback_MailSubject"] = "Tweak Firmware {0} — обратная связь",
            ["Feedback_BodyNameLine"] = "Имя: {0}",
            ["Feedback_BodyReplyToLine"] = "Обратный адрес: {0}",
            ["Feedback_BodyVersionLine"] = "Версия: {0}",
            ["Feedback_BodyOsLine"] = "Система: {0}",
            ["Feedback_MailClientFailedLog"] = "Обратная связь: не удалось открыть почтовый клиент ({0}).",

            // ===================== Извлечение разделов =====================
            // Тексты журнала разбора дампа. Названия разметок, файловых систем и меток
            // в дампе не переводятся — это термины, по которым ищут в поиске и на форумах.
            ["Extract_StageNandGeometry"] = "Определение геометрии NAND",
            ["Extract_NandDumpDetected"] = "Обнаружен дамп NAND.",
            ["Extract_NandSearchingGeometry"] = "Определяются значения main и spare…",
            ["Extract_NandGeometryUnknown"] = "Определить main и spare не удалось — нужен ручной выбор.",
            ["Extract_NandGeometryFound"] = "main = {0}, spare = {1}.",
            ["Extract_DuneHdLayoutFound"] = "Раскладка страницы Dune HD.",
            ["Extract_StageCheckEmpty"] = "Проверка пустых разделов",
            ["Extract_CommentEmpty"] = "пустой",
            ["Extract_MbrRecordsHeader"] = "Запись   Тип    Смещение        Размер",
            ["Extract_MbrRecordLine"] = "{0}        {1}   {2}   {3}",
            ["Extract_GptHeaderAt"] = "Заголовок GPT по адресу {0}.",
            ["Extract_GptTableAt"] = "Таблица GPT по адресу {0}, записей: {1}.",
            ["Extract_GptDiskGuid"] = "GUID диска {0}.",
            ["Extract_GptHeaderMissing"] = "Запись MBR указывает на GPT по адресу {0}, но заголовка там нет.",
            ["Extract_GptBackupMissing"] = "Резервный заголовок GPT по адресу {0} не найден.",
            ["Extract_GptHeaderCorrupt"] = "Контрольная сумма заголовка GPT не сходится.",
            ["Extract_GptTableCorrupt"] = "Контрольная сумма таблицы GPT не сходится.",
            ["Extract_EbrAt"] = "EBR по адресу {0}.",
            ["Extract_EbrNotFound"] = "EBR по адресу {0} не найден.",
            ["Extract_EbrOutsideDump"] = "Следующая запись EBR ({0}) находится за пределами дампа.",
            ["Extract_EbrBadRecords"] = "Записи EBR по адресу {0} не прошли проверку.",
            ["Extract_EbrChainTooLong"] = "Цепочка EBR слишком длинная — разбор остановлен.",
            ["Extract_PartsStringFound"] = "Список разделов найден по адресу {0}:",
            ["Extract_PartsStringRecordRejected"] = "Запись «{0}» разобрать не удалось — пропущена.",
            ["Extract_PartsFromTable"] = "Разделов в таблице: {0}.",
            ["Extract_MtkLgTableFound"] = "Найдена таблица «{0}» по адресу {1}.",
            ["Extract_SonyFixedMapGn5ur"] = "Дамп Sony MediaTek eMMC, точная карта GN5UR/MT5835.",
            ["Extract_SonyFixedMapSkan"] = "Дамп Sony MediaTek eMMC, точная карта Skan_dump.",
            ["Extract_SonyFloatingMap"] = "Дамп Sony MediaTek eMMC, карта построена по найденным EXT4/FAT16/AVB.",
            ["Extract_LgNandMapFound"] = "Карта LG NAND: {0}, адрес таблицы {1}.",
            ["Extract_BadBlocksFound"] = "Плохих блоков в таблице: {0}.",
            ["Extract_NandBlockSize"] = "Блоков в дампе: {0}, размер блока {1}.",
            ["Extract_SamsungMarkers"] = "Метки Samsung: UPCH по адресу {0}, LPCH по адресу {1}.",
            ["Extract_BluerayLayout"] = "Раскладка Blu-ray: подстраниц на странице {0}, хвост {1} байт.",
            ["Extract_DuneProductId"] = "Product ID: {0}.",
            ["Extract_DuneBoardId"] = "Board ID: {0}.",
            ["Extract_DuneLicenseFound"] = "Найден файл лицензии, {0} байт.",
            ["Extract_PhilipsInfo"] = "Philips: модель {0}, серийный номер {1}, версия ПО {2}.",
            ["Extract_PhilipsInfoNotFound"] = "Модель и серийный номер в дампе не найдены.",
            ["Extract_PhilipsEeprom"] = "EEPROM Philips 24C64: модель {0}, серийный номер {1}.",
            ["Extract_StageScanFs"] = "Поиск файловых систем",
            ["Extract_VolumeExceedsPartition"] = "Размер тома {0} выходит за границу раздела, обрезан до {1}",
            ["Extract_Ext4Volume"] = "EXT4 «{0}» по адресу {1}, размер {2}.",
            ["Extract_Ext4BlockSize"] = "Размер блока {0} кБ.",
            ["Extract_Ext4Blocks"] = "Блоков {0}, свободно {1} ({2} %).",
            ["Extract_Ext4Inodes"] = "Инод {0}, свободно {1} ({2} %).",
            ["Extract_Ext4State"] = "Состояние: {0}.",
            ["Extract_Ext4ErrorPolicy"] = "При ошибке: {0}.",
            ["Extract_Ext4Uuid"] = "UUID {0}.",
            ["Extract_Ext4LastMounted"] = "Последний путь монтирования: {0}.",
            ["Extract_Ext4StateClean"] = "размонтирована правильно",
            ["Extract_Ext4StateErrors"] = "обнаружены ошибки",
            ["Extract_Ext4StateOrphans"] = "идёт восстановление",
            ["Extract_Ext4StateUnknown"] = "неизвестно",
            ["Extract_Ext4PolicyContinue"] = "продолжать",
            ["Extract_Ext4PolicyReadOnly"] = "перемонтировать только для чтения",
            ["Extract_Ext4PolicyPanic"] = "останавливаться",
            ["Extract_SquashFsVolume"] = "SQUASHFS {0} {1} по адресу {2}, размер {3}.",
            ["Extract_SquashFsSwapped"] = "(обратный порядок байт)",
            ["Extract_SquashFsBlockSize"] = "Размер блока {0} кБ.",
            ["Extract_SquashFsCompression"] = "Сжатие: {0}.",
            ["Extract_SquashFsCorrupt"] = "размер блока не сходится с его логарифмом",
            ["Extract_RomFsVolume"] = "ROMFS «{0}» по адресу {1}, размер {2}.",
            ["Extract_CramFsVolume"] = "CRAMFS «{0}» по адресу {1}, размер {2}.",
            ["Extract_VdfsVolume"] = "VDFS «{0}» по адресу {1}, размер {2}.",
            ["Extract_VdfsDriver"] = "Драйвер {0}, размер блока {1} кБ.",
            ["Extract_TarVolume"] = "TAR «{0}» по адресу {1}, размер {2}, файлов {3}.",
            ["Extract_FatVolume"] = "{0} «{1}» по адресу {2}, размер {3}.",
            ["Extract_FatGeometry"] = "Сектор {0} байт, кластер {1} байт.",
            ["Extract_FatClusters"] = "Кластеров {0}, свободно {1} ({2} %).",
            ["Extract_AndroidHeader"] = "Сведения о прошивке Android:",
            ["Extract_AndroidNotFound"] = "Файл build.prop в дампе не найден.",
            ["Extract_AndroidBrand"] = "Марка: {0}",
            ["Extract_AndroidName"] = "Название: {0}",
            ["Extract_AndroidDevice"] = "Устройство: {0}",
            ["Extract_AndroidRelease"] = "Версия Android: {0}",
            ["Extract_AndroidManufacturer"] = "Изготовитель: {0}",
            ["Extract_AndroidPlatform"] = "Платформа: {0}",
            ["Extract_AndroidBoard"] = "Плата: {0}",
            ["Extract_AndroidModel"] = "Модель: {0}",
            ["Extract_AndroidSwVersion"] = "Версия ПО: {0}",
            ["Extract_AndroidHwBoard"] = "Шасси: {0}",
            ["Extract_AndroidDisplaySize"] = "Диагональ: {0}",
            ["Extract_FileSize"] = "Размер файла {0} ({1:N0} байт).",
            ["Extract_LayoutFound"] = "Опознана разметка {0}.",
            ["Extract_LayoutNotRecognised"] = "Разметку опознать не удалось.",
            ["Extract_PartsTotal"] = "Разделов в списке: {0}.",
            ["Extract_SearchFileSystemsQuestion"] = "Искать файловые системы внутри разделов?",
            ["Extract_NotEnoughSpace"] = "Нужно {0}, а свободно {1}.",
            ["Extract_PartitionWritten"] = "Извлечён раздел {0}.",
            ["Extract_StageSplitNand"] = "Разделение на main и spare",
            ["Extract_NandSplitDone"] = "Записано: main {0:N0} байт, spare {1:N0} байт.",
            ["Extract_Title"] = "Извлечение разделов",
            ["Extract_DumpLabel"] = "Дамп прошивки",
            ["Extract_OutputPlaceholder"] = "Не выбрана — рядом с дампом",
            ["Extract_SearchFileSystemsCheckbox"] = "Искать файловые системы внутри разделов",
            ["Extract_StartButton"] = "Начать",
            ["Extract_ExtractButton"] = "Извлечь отмеченные",
            ["Extract_SaveUdevButton"] = "Сохранить .udev",
            ["Extract_SplitNandButton"] = "Разделить на main и spare",
            ["Extract_AnalysisProgressLabel"] = "Анализ файла",
            ["Extract_PartitionsTitle"] = "Найденные разделы",
            ["Extract_SelectAllTooltip"] = "Отметить все разделы или снять все отметки",
            ["Extract_ShowPhysicalCheckbox"] = "Адреса со spare",
            ["Extract_ColumnNumber"] = "Номер",
            ["Extract_ColumnOffset"] = "Смещение",
            ["Extract_ColumnLength"] = "Размер",
            ["Extract_ColumnFs"] = "ФС",
            ["Extract_ColumnName"] = "Имя",
            ["Extract_ColumnBadBlocks"] = "Bad Block",
            ["Extract_ColumnComment"] = "Примечание",
            ["Extract_NoResultYet"] = "Выберите дамп и нажмите «Начать».",
            ["Extract_ResultSummary"] = "Разметка: {0}. Разделов: {1}.",
            ["Extract_UnknownMark"] = "неизвестна",
            ["Extract_AnalysisStarted"] = "Разбор дампа: {0}",
            ["Extract_ExtractDone"] = "Извлечено разделов: {0}.\nПапка: {1}",
            ["Extract_NothingSelected"] = "Не отмечен ни один раздел.",
            ["Extract_SplitDone"] = "Готово.\n{0}\n{1}",
            ["Extract_UdevFilter"] = "Файлы устройств (*.udev)|*.udev|Все файлы (*.*)|*.*",
            ["Extract_UdevSaved"] = "Файл .udev сохранён: {0}",
            ["Extract_ArtifactSaved"] = "Сохранён файл {0}",
            ["Extract_ArtifactFailed"] = "Не удалось сохранить {0}: {1}",
            ["Extract_RenameButton"] = "Переименовать дамп",
            ["Extract_RenameQuestionTitle"] = "Переименовать дамп?",
            ["Extract_RenameQuestion"] = "Имя файла будет собрано из модели, версии и серийного номера:\n\n{0}",
            ["Extract_RenameDone"] = "Файл переименован: {0}",
            ["Extract_RenameFailed"] = "Не удалось переименовать файл: {0}",
            ["Extract_RenameExists"] = "Файл с таким именем уже есть в этой папке.",
            ["Extract_GeometryQuestionTitle"] = "Размер страницы NAND",
            ["Extract_GeometryQuestion"] = "Определить размер страницы по дампу не удалось. Выберите значение вручную.",
            ["Extract_GeometryOption"] = "{0}. main = {1}, spare = {2}",
            ["Extract_GeometryOptionNoSpare"] = "{0}. Без spare — разбирать как сплошной дамп",

            // ===================== Заглушки разделов в разработке =====================
            ["Placeholder_PartitionMergeTitle"] = "Объединение разделов",
            ["Placeholder_PartitionMergeText"] = "Обратная сборка дампа из разделов, вытащенных на вкладке «Извлечение разделов».",
        };

        private static readonly Dictionary<string, string> En = new()
        {
            // ===================== Common =====================
            ["Common_Error"] = "Error",
            ["Common_ErrorLog"] = "Error: {0}",
            ["Common_PauseButton"] = "Pause",
            ["Common_ResumeButton"] = "Resume",
            ["Common_FileNotFoundTitle"] = "File not found",
            ["Common_FileNotFoundMessage"] = "There is no file at the given path:\n{0}",
            ["Common_BrowseButton"] = "📁 Browse…",
            ["Common_AllFilesFilter"] = "All files (*.*)|*.*",
            ["Common_TextFileFilter"] = "Text file (*.txt)|*.txt",
            ["Common_BinFileFilter"] = "BIN files (*.bin)|*.bin|All files (*.*)|*.*",
            ["Common_LogOpenButton"] = "Open",
            ["Common_LogSaveButton"] = "Save",
            ["Common_LogClearButton"] = "Clear",
            ["Common_LogCopyButton"] = "Copy",
            ["Common_LogResizeTooltip"] = "Drag to change the log height",
            ["Common_CopyHashTooltip"] = "Copy the hash",
            ["Common_CopiedTooltip"] = "Copied",
            ["Common_HashConfirmedLabel"] = "SHA-256 confirmed:",
            ["Common_LogTitle"] = "Log",
            ["Common_ProgressTitle"] = "Progress",
            ["Common_OpenFolderCheckbox"] = "Open the result folder",
            ["Common_SaveLogFailed"] = "Failed to save the log:\n{0}",
            ["Common_FileProgressLabel"] = "{0} — file {1} of {2}",
            ["Common_OverwriteChoice"] = "Overwrite",
            ["Common_CancelChoice"] = "Cancel",
            ["Common_DigitsOnly"] = "Digits only are allowed",
            ["Common_DestinationFolderLabel"] = "Destination folder",
            ["Common_NoFileSelected"] = "No file selected — you can drag one here",
            ["Common_NoFolderSelected"] = "No folder selected — you can drag one here",
            ["Common_SelectFileHint"] = "Select the file you need to get started.",
            ["Common_CancelButton"] = "Cancel",
            ["Common_OkButton"] = "OK",
            ["Common_CannotStartTitle"] = "Cannot start",
            ["Common_LowSpaceTitle"] = "Not enough space",
            ["Common_DoneTitle"] = "Done",
            ["Common_VerifyErrorTitle"] = "Verification failed",
            ["Common_CancelledTitle"] = "Cancelled",
            ["Common_DeletingIncompleteLog"] = "Deleting incomplete files ({0})...",
            ["Common_DeletedLog"] = "Deleted: {0}",
            ["Common_DeleteFailedLog"] = "Failed to delete {0}: {1}",
            ["Common_ClipboardFailedLog"] = "Could not write to the clipboard ({0}).",
            ["Common_UnexpectedErrorTitle"] = "Unexpected error",
            ["Common_UnexpectedErrorMessage"] = "Something the program did not account for happened:\n{0}\n\nIt kept running, but the result of that action may be incomplete. The details are in the log.",
            ["Common_UnexpectedErrorLog"] = "Unexpected error ({0}): {1} — {2}",
            ["Common_OutputNotUsableMessage"] = "This save location cannot be used:\n{0}\n\nCheck the path: the drive must exist and be writable. For network folders the program cannot always find out the free space — in that case clear the “Check free disk space” checkbox.",
            ["Common_GeneralInfoTitle"] = "General info",
            ["Common_ParametersTitle"] = "Parameters",
            ["Common_CheckDiskSpaceCheckbox"] = "Check free space on the disk",
            ["Common_CurrentFileProgressLabel"] = "Current file",
            ["Common_OpenFolderFailedLog"] = "Failed to open the folder: {0}",
            ["Update_GitHubRespondedError"] = "GitHub responded: {0} {1}",
            ["Update_CheckFailedError"] = "Failed to check for updates: {0}",

            // ===================== Sizes (SizeFormatHelper) =====================
            ["Size_GbFormat"] = "{0:F2} GB ({1:N0} bytes)",
            ["Size_MbFormat"] = "{0:F2} MB ({1:N0} bytes)",

            // ===================== Core: exceptions and log =====================
            ["Core_SourceFileNotFound"] = "Source file not found",
            ["Core_ChainBaseFileNotFound"] = "Base file of the chain not found",
            ["Core_ChainPartMissing"] = "Part {0} is missing while part {1} exists: the chain is broken and the result would be incomplete.",
            ["Core_CannotDetermineDrive"] = "Could not determine the drive for path: {0}",
            ["Log_Created"] = "Log created",
            ["Log_Cleared"] = "Log cleared",
            ["Log_TrimmedOlderEntries"] = "— older entries ({0}) were removed to keep the log from growing —",
            ["Log_AppStarted"] = "Application started",
            ["Log_TimestampLabel"] = "Date and time",
            ["Log_PartCreated"] = "Created {0} (file {1} of {2})",
            ["Log_PartFilled"] = "File {0} filled ({1:N0} bytes)",
            ["Log_PartFinished"] = "File {0} finished ({1:N0} bytes)",
            ["Log_ClosingFile"] = "Writing {0} out to disk... (may take a while: the file is large)",
            ["Log_VerifyingHash"] = "Verifying SHA-256: re-reading all parts in sequence...",
            ["Log_HashMatches"] = "SHA-256 matches — no bytes lost",
            ["Log_HashMismatchError"] = "Error: SHA-256 does not match — check the result.",
            ["Log_ChainFound"] = "Found parts in the chain: {0} (total {1:N0} bytes)",
            ["Log_ReadingPart"] = "Reading {0} (file {1} of {2})",
            ["Log_MergeFinished"] = "Merge finished: {0} ({1:N0} bytes)",

            // ===================== Shell/navigation/auto-update =====================
            ["Shell_NavConvert"] = "Convert",
            ["Shell_NavMerge"] = "Merge file",
            ["Shell_NavVerify"] = "Verify SHA-256",
            ["Shell_NavExtract"] = "Extract partitions",
            ["Shell_NavPartitionMerge"] = "Merge partitions",
            ["Shell_NavSettings"] = "Settings",
            ["Shell_NavAbout"] = "About",
            ["Shell_FilesGroupHeader"] = "FILES",
            ["Shell_PartitionsGroupHeader"] = "PARTITIONS",
            ["Shell_MiscGroupHeader"] = "OTHER",
            ["Shell_SystemGroupHeader"] = "SYSTEM",
            ["Shell_WindowTitle"] = "Tweak Firmware",
            ["Shell_TitleBarTitle"] = "Tweak Firmware",
            ["Shell_MenuToggleTooltip"] = "Show or hide the menu",
            ["Shell_UpdateBanner"] = "Version {0} is available",
            ["Shell_UpdateDownloadButton"] = "Download",
            ["Shell_UpdateInstallButton"] = "Install and restart",
            ["Shell_UpdateReadyBanner"] = "Version {0} is downloaded and ready to install",
            ["Shell_UpdateWaitingForOperation"] = "Installing will be available once the operation finishes",
            ["Shell_UpdateDownloadCancelledLog"] = "Update download cancelled",
            ["Shell_UpdateInstallerMissingMessage"] = "The downloaded installer is missing — try downloading the update again.",
            ["Shell_LaterButton"] = "Later",
            ["Shell_DownloadingUpdate"] = "Downloading update... {0:F0}%",
            ["Shell_Installing"] = "Installing...",
            ["Shell_UpdateErrorTitle"] = "Update error",
            ["Shell_UpdateErrorMessage"] = "Failed to download or install the update:\n{0}",
            ["Shell_UpdateFoundLog"] = "Update found: version {0} (current {1})",
            ["Shell_UpdateDownloadStartLog"] = "Started downloading update {0}: {1}",
            ["Shell_UpdateDownloadedLog"] = "Update downloaded and ready to install",
            ["Shell_UpdateErrorLog"] = "Auto-update error: {0}",
            ["Shell_Placeholder_InDevelopment"] = "Under development",

            // ===================== Convert =====================
            ["Convert_Title"] = "Convert",
            ["Convert_SourceFileLabel"] = "Source .bin file",
            ["Convert_ProgrammerModelLabel"] = "Programmer model",
            ["Convert_LimitLabel"] = "Limit per file",
            ["Convert_LimitPlaceholder"] = "In bytes",
            ["Convert_SourceInsideOutputMessage"] = "The source file sits where the program is about to write, and one of the files it creates would land on top of it.\n\nChoose a different destination folder or a different file name.",
            ["Convert_VerifyHashCheckbox"] = "Verify SHA-256",
            ["Convert_OverallProgressLabel"] = "Conversion",
            ["Convert_HashProgressLabel"] = "SHA-256 algorithm",
            ["Convert_StartButton"] = "Start",
            ["Convert_CustomPresetName"] = "Custom settings",
            ["Convert_ChooseOutputFolderTitle"] = "Choose the output folder",
            ["Convert_ShowAllFilesButton"] = "Show all files",
            ["Convert_SourceSizeLine"] = "Source file size: {0}",
            ["Convert_ExpectedCountLine"] = "Expected file count: {0}",
            ["Convert_InvalidLimitLine"] = "Enter a part size of at least 1024 bytes",
            ["Convert_TooManyFilesLine"] = "Too many files to list individually",
            ["Convert_EachFileSizeHeader"] = "Size of each file:",
            ["Convert_FileSizeLine"] = "File {0}: {1}",
            ["Convert_MoreFilesLine"] = "… and {0} more file(s)",
            ["Convert_CollapseList"] = "Collapse the list",
            ["Convert_ShowAllFilesCount"] = "Show all {0} files",
            ["Convert_SelectSourceFirst"] = "Select an existing source file.",
            ["Convert_SpecifyOutputFolder"] = "Specify the output folder.",
            ["Convert_InvalidPartSize"] = "Invalid part size.",
            ["Convert_ConflictTitle"] = "Files already exist",
            ["Convert_ConflictMessage"] = "The folder already contains files named \"{0}\" (or its parts).",
            ["Convert_NewFolderNearby"] = "New folder",
            ["Convert_ConflictLog"] = "Name conflict detected — using a new folder: {0}",
            ["Convert_LowSpaceMessage"] = "Source file size: {0}\nRequired (with 5% margin): {1}\nAvailable: {2}\nMissing: {3}",
            ["Convert_StartLog"] = "Starting conversion: {0} -> {1}\\{2} (max {3:N0} bytes/file)",
            ["Convert_FinishedLog"] = "Conversion finished. Files: {0}, total bytes: {1:N0}",
            ["Convert_DoneVerifiedMessage"] = "Conversion completed successfully.\n\nFiles created: {0}",
            ["Convert_VerifyErrorMessage"] = "Checksums do not match — the data is corrupted.",
            ["Convert_HashSourceLabel"] = "Source file:",
            ["Convert_HashResultLabel"] = "Files created:",
            ["Convert_DoneMessage"] = "Conversion completed.\n\nFiles created: {0}",
            ["Convert_CancelledLog"] = "Conversion cancelled by the user",
            ["Convert_CancelledMessage"] = "Conversion cancelled.\nIncomplete files deleted: {0}",
            ["Convert_DiskFullMessage"] = "The disk ran out of space while writing.\n\nThe operation was interrupted, incomplete files ({0}) were deleted — free up space and try again.",
            ["Convert_ErrorMessage"] = "Could not finish the conversion:\n{0}\n\nIncomplete files ({1}) were deleted.",
            ["Convert_ResumedLog"] = "Operation resumed by the user",
            ["Convert_PausedLog"] = "Operation paused by the user",

            // ===================== Merge =====================
            ["Merge_Title"] = "Merge file",
            ["Merge_SourceFileFilter"] = "BIN and parts (*.bin;*.part*)|*.bin;*.bin.part*|All files (*.*)|*.*",
            ["Merge_AnyChainPartLabel"] = "Any part of the chain",
            ["Merge_ExpectedHashLabel"] = "Expected SHA-256",
            ["Merge_ExpectedHashTooltip"] = "If you know the original file's hash, paste it here to verify",
            ["Merge_ExpectedHashPlaceholder"] = "Optional — paste it if you know it",
            ["Merge_OutputInsideChainMessage"] = "The result file is one of the files in the chain being merged, and merging would destroy it: it is emptied before anything gets to read it.\n\nChoose a different name or a different folder for the result.",
            ["Merge_ExpectedHashHint"] = "That does not look like a SHA-256: it needs {0} characters, digits and the letters A–F",
            ["Merge_ExpectedHashInvalidMessage"] = "The “Expected SHA-256” field is filled in, but that is not a hash.\n\nA SHA-256 is exactly {0} characters, digits and the letters A–F. Check that the string was copied in full, or clear the field — the merge will then run without the comparison.",
            ["Merge_ResultSizeLine"] = "Final file size: {0}",
            ["Merge_OverallProgressLabel"] = "Merge",
            ["Merge_StartButton"] = "Start",
            ["Merge_ChainFoundInfo"] = "Parts found: {0} ({1}). First: {2}",
            ["Merge_ChainNamingHint"] = "Parts are found by name: emmc.bin, emmc.bin.part1, emmc.bin.part2 and so on in order.",
            ["Merge_UnevenPartsWarning"] = "Chain parts differ in size — part {0} stands out. That happens when another program split the chain; if this one did, the part may be an incomplete copy. Verify the result by SHA-256.",
            ["Merge_ChainResolveError"] = "Could not determine the chain: {0}",
            ["Merge_SelectSourceFirst"] = "Select a file from the part chain.",
            ["Merge_SpecifyOutputFile"] = "Specify the result file.",
            ["Merge_FileExistsTitle"] = "File already exists",
            ["Merge_FileExistsMessage"] = "File \"{0}\" already exists.",
            ["Merge_NewNameNearby"] = "New name",
            ["Merge_ConflictLog"] = "Name conflict detected — using a new file: {0}",
            ["Merge_ChainCheckErrorMessage"] = "Failed to check the part chain:\n{0}",
            ["Merge_LowSpaceMessage"] = "Size of the data being merged: {0}\nRequired (with 5% margin): {1}\nAvailable: {2}\nMissing: {3}",
            ["Merge_StartLog"] = "Starting merge: {0} -> {1}",
            ["Merge_FinishedLog"] = "Merge finished. Parts: {0}, bytes: {1:N0}",
            ["Merge_ResultHashLog"] = "Result SHA-256: {0}",
            ["Merge_HashMatchLog"] = "Comparison with the specified hash: matches ✓",
            ["Merge_HashMismatchLog"] = "Comparison with the specified hash: does not match!",
            ["Merge_ResultMatchMessage"] = "Merge completed.\n\nSHA-256 matches the specified one.",
            ["Merge_ResultMismatchMessage"] = "SHA-256 does not match the expected one.",
            ["Merge_HashExpectedLabel"] = "Expected:",
            ["Merge_HashActualLabel"] = "Got:",
            ["Merge_DoneMessage"] = "Merge completed.\n\nParts: {0}\nSize: {1:N0} bytes",
            ["Merge_HashResultLabel"] = "SHA-256 of the merged file:",
            ["Merge_CancelledLog"] = "Merge cancelled by the user",
            ["Merge_CancelledMessage"] = "Merge cancelled.\nThe incomplete result file was deleted.",
            ["Merge_DiskFullMessage"] = "The disk ran out of space while writing.\n\nThe operation was interrupted, the incomplete result file was deleted — free up space and try again.",
            ["Merge_ErrorMessage"] = "Could not finish the merge:\n{0}\n\nThe incomplete result file was deleted.",
            ["Merge_ResumedLog"] = "Operation resumed by the user",
            ["Merge_PausedLog"] = "Operation paused by the user",

            // ===================== Verify SHA-256 =====================
            ["Verify_Title"] = "Verify SHA-256",
                        ["Verify_FileLabel"] = "File {0}",
            ["Verify_AddFileButton"] = "Add a file",
            ["Verify_RemoveFileTooltip"] = "Remove this file",
            ["Verify_MaxFilesNote"] = "Maximum: {0} files",
            ["Verify_SelectFilesHint"] = "Select the files you need to get started.",
            ["Verify_FilesSelectedLine"] = "Files selected: {0}",
            ["Verify_InfoFileLine"] = "{0} — {1}",
            ["Verify_InfoFileMissingLine"] = "{0} — file not found",
            ["Verify_SizesDifferNote"] = "The files differ in size — their hashes cannot be the same.",
            ["Verify_CompareProgressLabel"] = "Comparison",
            ["Verify_CompareButton"] = "Start",
                        ["Verify_SelectBothFiles"] = "Choose files to compare — at least two are needed.",
            ["Verify_FilesMissingMessage"] = "Files not found:\n{0}",
            ["Verify_CompareLog"] = "Comparing hashes: {0} files",
            ["Verify_FileLabelProgress"] = "File {0} of {1} — {2}",
            ["Verify_HashesMatchLog"] = "Hashes match",
            ["Verify_HashesMismatchLog"] = "Hashes do not match",
            ["Verify_ResultTitle"] = "Result",
            ["Verify_NoResultYet"] = "No comparison has been run yet",
            ["Verify_CancelledMessage"] = "The comparison was cancelled — hashes were not computed for every file.",
            ["Verify_AllIdenticalHeadline"] = "All files are identical",
            ["Verify_AllIdenticalSubline"] = "Checked: {0} files — all share the same SHA-256.",
            ["Verify_DifferenceHeadline"] = "A difference was found",
            ["Verify_DifferenceSubline"] = "{0} of {1} files are identical.",
            ["Verify_AllDifferentSubline"] = "All {0} files differ from each other.",
            ["Verify_GroupTitle"] = "SHA-256 of group {0} — files: {1}",
            ["Verify_SingleGroupTitle"] = "SHA-256",
            ["Verify_HashErrorMessage"] = "Could not compute the hash:\n{0}",

            // ===================== Settings =====================
            ["Settings_Title"] = "Settings",
            ["Settings_ThemeTitle"] = "Theme",
            ["Settings_ThemeLight"] = "Light",
            ["Settings_ThemeDark"] = "Dark",
            ["Settings_ThemeSystem"] = "Same as system",
            ["Settings_LanguageTitle"] = "Interface language",
            // Названия языков не переводятся: их читает тот, кто нужного языка
            // ещё не выбрал, — «Русский» ему понятнее, чем «Russian».
            ["Settings_LanguageRu"] = "Русский",
            ["Settings_LanguageEn"] = "English",
            ["Settings_UseDefaultPathCheckbox"] = "Default path",
            ["Settings_ChooseConvertFolderTitle"] = "Default folder for conversion",
            ["Settings_ChooseMergeFolderTitle"] = "Default folder for merging",
            ["Settings_ChooseExtractFolderTitle"] = "Default folder for partition extraction",
            ["Settings_ConvertFolderTitle"] = "Convert folder",
            ["Settings_MergeFolderTitle"] = "Merge folder",
            ["Settings_ExtractFolderTitle"] = "Extract folder",
            ["Settings_ClearLogTitle"] = "Application log",
            ["Settings_ClearLogDescription"] = "Removes every log entry — both from the “Log” card on the working tabs and from the file on disk.",
            ["Settings_ClearLogButton"] = "Clear the log",
            ["Settings_LogClearedMessage"] = "The log has been cleared.",

            // ===================== About =====================
            ["About_Title"] = "About",
            ["About_TaglineText"] = "A program for working with firmware: converting and reassembling dumps, extracting and merging partitions, checking hash sums.",
            ["About_UpdatesTitle"] = "Updates",
            ["About_UpdatesDescription"] = "Check whether a newer version of the program is available.",
            ["About_CheckUpdatesButton"] = "Check for updates",
            ["About_Checking"] = "Checking...",
            ["About_UpdateAvailable"] = "A new version is available: {0} (see the notice above)",
            ["About_UpToDate"] = "You have the latest version.",
            ["About_CheckUpdatesTitle"] = "Check for updates",
            ["About_DevelopmentTitle"] = "Development",
            ["About_DevelopmentText"] = "Alxmak and a few chatbots.",
            ["About_PersonalUseText"] = "This program was created for personal use.",
            ["About_SourcesTitle"] = "Sources",
            ["About_SourcesDescription"] = "Forums and sites whose materials helped in the work on the program.",
            ["About_VersionText"] = "Version {0}",

            // ===================== Feedback =====================
            ["Feedback_Title"] = "Feedback",
            ["Feedback_Intro"] = "I will be grateful for your feedback, suggestions and bug reports.",
            ["Feedback_WriteButton"] = "Write an email",
            ["Feedback_CopyAddressButton"] = "Copy the address",
            ["Feedback_AddressCopiedButton"] = "Address copied",
            ["Feedback_CopyFailedStatus"] = "Could not copy: another application is holding the clipboard, please try again.",
            ["Feedback_NoMailClientCopied"] = "Could not open a mail client — it seems none is set up in the system. The address {0} has been copied to the clipboard, please write manually.",
            ["Feedback_NoMailClient"] = "Could not open a mail client — it seems none is set up in the system. Please write manually to {0}.",
            ["Feedback_MailSubject"] = "Tweak Firmware {0} — feedback",
            ["Feedback_BodyNameLine"] = "Name: {0}",
            ["Feedback_BodyReplyToLine"] = "Reply to: {0}",
            ["Feedback_BodyVersionLine"] = "Version: {0}",
            ["Feedback_BodyOsLine"] = "System: {0}",
            ["Feedback_MailClientFailedLog"] = "Feedback: could not open a mail client ({0}).",

            // ===================== Extract partitions =====================
            ["Extract_StageNandGeometry"] = "Detecting NAND geometry",
            ["Extract_NandDumpDetected"] = "NAND dump detected.",
            ["Extract_NandSearchingGeometry"] = "Finding values of main and spare…",
            ["Extract_NandGeometryUnknown"] = "Could not determine main and spare — manual choice required.",
            ["Extract_NandGeometryFound"] = "main = {0}, spare = {1}.",
            ["Extract_DuneHdLayoutFound"] = "Dune HD page layout.",
            ["Extract_StageCheckEmpty"] = "Checking for empty partitions",
            ["Extract_CommentEmpty"] = "empty",
            ["Extract_MbrRecordsHeader"] = "Record   Type   Offset          Length",
            ["Extract_MbrRecordLine"] = "{0}        {1}   {2}   {3}",
            ["Extract_GptHeaderAt"] = "GPT header at {0}.",
            ["Extract_GptTableAt"] = "GPT table at {0}, {1} entries.",
            ["Extract_GptDiskGuid"] = "Disk GUID {0}.",
            ["Extract_GptHeaderMissing"] = "An MBR record points to a GPT at {0}, but there is no header there.",
            ["Extract_GptBackupMissing"] = "Backup GPT header at {0} not found.",
            ["Extract_GptHeaderCorrupt"] = "GPT header checksum does not match.",
            ["Extract_GptTableCorrupt"] = "GPT table checksum does not match.",
            ["Extract_EbrAt"] = "EBR at {0}.",
            ["Extract_EbrNotFound"] = "No EBR at {0}.",
            ["Extract_EbrOutsideDump"] = "The next EBR record ({0}) lies outside the dump.",
            ["Extract_EbrBadRecords"] = "EBR records at {0} failed validation.",
            ["Extract_EbrChainTooLong"] = "The EBR chain is too long — parsing stopped.",
            ["Extract_PartsStringFound"] = "Partition list found at {0}:",
            ["Extract_PartsStringRecordRejected"] = "Could not parse the record \u201C{0}\u201D — skipped.",
            ["Extract_PartsFromTable"] = "Partitions in the table: {0}.",
            ["Extract_MtkLgTableFound"] = "Found table \u201C{0}\u201D at {1}.",
            ["Extract_SonyFixedMapGn5ur"] = "Sony MediaTek eMMC dump, fixed GN5UR/MT5835 map.",
            ["Extract_SonyFixedMapSkan"] = "Sony MediaTek eMMC dump, fixed Skan_dump map.",
            ["Extract_SonyFloatingMap"] = "Sony MediaTek eMMC dump, map built from the EXT4/FAT16/AVB anchors found.",
            ["Extract_LgNandMapFound"] = "LG NAND map: {0}, table at {1}.",
            ["Extract_BadBlocksFound"] = "Bad blocks in the table: {0}.",
            ["Extract_NandBlockSize"] = "Blocks in the dump: {0}, block size {1}.",
            ["Extract_SamsungMarkers"] = "Samsung markers: UPCH at {0}, LPCH at {1}.",
            ["Extract_BluerayLayout"] = "Blu-ray layout: {0} subpages per page, {1} trailing bytes.",
            ["Extract_DuneProductId"] = "Product ID: {0}.",
            ["Extract_DuneBoardId"] = "Board ID: {0}.",
            ["Extract_DuneLicenseFound"] = "License file found, {0} bytes.",
            ["Extract_PhilipsInfo"] = "Philips: model {0}, serial {1}, software version {2}.",
            ["Extract_PhilipsInfoNotFound"] = "Model and serial number were not found in the dump.",
            ["Extract_PhilipsEeprom"] = "Philips 24C64 EEPROM: model {0}, serial {1}.",
            ["Extract_StageScanFs"] = "Searching for file systems",
            ["Extract_VolumeExceedsPartition"] = "Volume size {0} runs past the partition boundary, trimmed to {1}",
            ["Extract_Ext4Volume"] = "EXT4 \u201C{0}\u201D at {1}, size {2}.",
            ["Extract_Ext4BlockSize"] = "Block size {0} kB.",
            ["Extract_Ext4Blocks"] = "Blocks {0}, free {1} ({2} %).",
            ["Extract_Ext4Inodes"] = "Inodes {0}, free {1} ({2} %).",
            ["Extract_Ext4State"] = "State: {0}.",
            ["Extract_Ext4ErrorPolicy"] = "On error: {0}.",
            ["Extract_Ext4Uuid"] = "UUID {0}.",
            ["Extract_Ext4LastMounted"] = "Last mounted at: {0}.",
            ["Extract_Ext4StateClean"] = "cleanly unmounted",
            ["Extract_Ext4StateErrors"] = "errors detected",
            ["Extract_Ext4StateOrphans"] = "orphans being recovered",
            ["Extract_Ext4StateUnknown"] = "unknown",
            ["Extract_Ext4PolicyContinue"] = "continue",
            ["Extract_Ext4PolicyReadOnly"] = "remount read-only",
            ["Extract_Ext4PolicyPanic"] = "panic",
            ["Extract_SquashFsVolume"] = "SQUASHFS {0} {1} at {2}, size {3}.",
            ["Extract_SquashFsSwapped"] = "(byte-swapped)",
            ["Extract_SquashFsBlockSize"] = "Block size {0} kB.",
            ["Extract_SquashFsCompression"] = "Compression: {0}.",
            ["Extract_SquashFsCorrupt"] = "block size does not match its logarithm",
            ["Extract_RomFsVolume"] = "ROMFS \u201C{0}\u201D at {1}, size {2}.",
            ["Extract_CramFsVolume"] = "CRAMFS \u201C{0}\u201D at {1}, size {2}.",
            ["Extract_VdfsVolume"] = "VDFS \u201C{0}\u201D at {1}, size {2}.",
            ["Extract_VdfsDriver"] = "Driver {0}, block size {1} kB.",
            ["Extract_TarVolume"] = "TAR \u201C{0}\u201D at {1}, size {2}, {3} files.",
            ["Extract_FatVolume"] = "{0} \u201C{1}\u201D at {2}, size {3}.",
            ["Extract_FatGeometry"] = "Sector {0} bytes, cluster {1} bytes.",
            ["Extract_FatClusters"] = "Clusters {0}, free {1} ({2} %).",
            ["Extract_AndroidHeader"] = "Android firmware details:",
            ["Extract_AndroidNotFound"] = "build.prop was not found in the dump.",
            ["Extract_AndroidBrand"] = "Brand: {0}",
            ["Extract_AndroidName"] = "Name: {0}",
            ["Extract_AndroidDevice"] = "Device: {0}",
            ["Extract_AndroidRelease"] = "Android version: {0}",
            ["Extract_AndroidManufacturer"] = "Manufacturer: {0}",
            ["Extract_AndroidPlatform"] = "Platform: {0}",
            ["Extract_AndroidBoard"] = "Board: {0}",
            ["Extract_AndroidModel"] = "Model: {0}",
            ["Extract_AndroidSwVersion"] = "Software version: {0}",
            ["Extract_AndroidHwBoard"] = "Chassis: {0}",
            ["Extract_AndroidDisplaySize"] = "Display size: {0}",
            ["Extract_FileSize"] = "File size {0} ({1:N0} bytes).",
            ["Extract_LayoutFound"] = "Layout recognised: {0}.",
            ["Extract_LayoutNotRecognised"] = "The layout could not be recognised.",
            ["Extract_PartsTotal"] = "Partitions in the list: {0}.",
            ["Extract_SearchFileSystemsQuestion"] = "Search for file systems inside the partitions?",
            ["Extract_NotEnoughSpace"] = "{0} needed, {1} available.",
            ["Extract_PartitionWritten"] = "Extracted partition {0}.",
            ["Extract_StageSplitNand"] = "Splitting into main and spare",
            ["Extract_NandSplitDone"] = "Written: main {0:N0} bytes, spare {1:N0} bytes.",
            ["Extract_Title"] = "Extract partitions",
            ["Extract_DumpLabel"] = "Firmware dump",
            ["Extract_OutputPlaceholder"] = "Not set — next to the dump",
            ["Extract_SearchFileSystemsCheckbox"] = "Search for file systems inside partitions",
            ["Extract_StartButton"] = "Start",
            ["Extract_ExtractButton"] = "Extract selected",
            ["Extract_SaveUdevButton"] = "Save .udev",
            ["Extract_SplitNandButton"] = "Split into main and spare",
            ["Extract_AnalysisProgressLabel"] = "File analysis",
            ["Extract_PartitionsTitle"] = "Partitions found",
            ["Extract_SelectAllTooltip"] = "Select every partition or clear all marks",
            ["Extract_ShowPhysicalCheckbox"] = "Addresses with spare",
            ["Extract_ColumnNumber"] = "Number",
            ["Extract_ColumnOffset"] = "Offset",
            ["Extract_ColumnLength"] = "Length",
            ["Extract_ColumnFs"] = "FS",
            ["Extract_ColumnName"] = "Name",
            ["Extract_ColumnBadBlocks"] = "Bad Block",
            ["Extract_ColumnComment"] = "Comment",
            ["Extract_NoResultYet"] = "Choose a dump and press \u201CStart\u201D.",
            ["Extract_ResultSummary"] = "Layout: {0}. Partitions: {1}.",
            ["Extract_UnknownMark"] = "unknown",
            ["Extract_AnalysisStarted"] = "Analysing dump: {0}",
            ["Extract_ExtractDone"] = "Partitions extracted: {0}.\nFolder: {1}",
            ["Extract_NothingSelected"] = "No partition is selected.",
            ["Extract_SplitDone"] = "Done.\n{0}\n{1}",
            ["Extract_UdevFilter"] = "Device files (*.udev)|*.udev|All files (*.*)|*.*",
            ["Extract_UdevSaved"] = ".udev file saved: {0}",
            ["Extract_ArtifactSaved"] = "Saved file {0}",
            ["Extract_ArtifactFailed"] = "Could not save {0}: {1}",
            ["Extract_RenameButton"] = "Rename the dump",
            ["Extract_RenameQuestionTitle"] = "Rename the dump?",
            ["Extract_RenameQuestion"] = "The file name will be built from the model, version and serial number:\n\n{0}",
            ["Extract_RenameDone"] = "File renamed: {0}",
            ["Extract_RenameFailed"] = "Could not rename the file: {0}",
            ["Extract_RenameExists"] = "A file with that name already exists in this folder.",
            ["Extract_GeometryQuestionTitle"] = "NAND page size",
            ["Extract_GeometryQuestion"] = "The page size could not be determined from the dump. Please choose it manually.",
            ["Extract_GeometryOption"] = "{0}. main = {1}, spare = {2}",
            ["Extract_GeometryOptionNoSpare"] = "{0}. No spare — treat the dump as flat",

            // ===================== In-development placeholders =====================
            ["Placeholder_PartitionMergeTitle"] = "Merge partitions",
            ["Placeholder_PartitionMergeText"] = "Putting a dump back together from the partitions pulled out on the Extract partitions tab.",
        };
    }
}
