using System.Collections.Generic;
using System.Globalization;

namespace TweakFirmware.Core.Localization
{
    /// <summary>
    /// Единое хранилище всех текстов интерфейса, диалогов и журнала — на русском и
    /// английском. Не .resx: строгая типизация через автогенерируемый Designer.cs
    /// требует специфичной MSBuild-конфигурации (Generator=MSBuild:Compile +
    /// StronglyTyped*-метаданные), у которой давняя история проблем в разных версиях
    /// .NET SDK при сборке без Visual Studio (именно так собирается релиз в CI —
    /// обычным "dotnet publish"). Обычный класс со словарями даёт тот же результат
    /// (тексты не смешаны с разметкой/кодом, один файл на язык, легко добавить
    /// третий язык) без риска, что сборка сломается на билд-сервере.
    ///
    /// Язык переключается через <see cref="SetLanguage"/> — его вызывает
    /// TweakFirmware.Services.LocalizationService (главное приложение) при старте
    /// и при выборе языка в настройках. Здесь же — общий формат размеров
    /// (SizeFormatHelper) и сообщения ядра (FileSplitter/FileMerger/HashHelper),
    /// поэтому файл лежит в Core, а не в основном проекте.
    /// </summary>
    public static class Strings
    {
        public const string DefaultLanguage = "ru";

        public static string CurrentLanguage { get; private set; } = DefaultLanguage;

        public static void SetLanguage(string code)
        {
            CurrentLanguage = code == "en" ? "en" : "ru";
        }

        public static string Get(string key)
        {
            var table = CurrentLanguage == "en" ? En : Ru;
            return table.TryGetValue(key, out var value) ? value : (Ru.TryGetValue(key, out var fallback) ? fallback : key);
        }

        /// <summary>string.Format с текущей культурой отображения (влияет на разделители чисел).</summary>
        public static string Format(string key, params object[] args) =>
            string.Format(CultureInfo.CurrentCulture, Get(key), args);

        private static readonly Dictionary<string, string> Ru = new()
        {
            // ===================== Общее =====================
            ["Common_Error"] = "Ошибка",
            ["Common_PauseButton"] = "Приостановить",
            ["Common_ResumeButton"] = "Возобновить",
            ["Common_FileNotFoundMessage"] = "Файл не найден.",
            ["Common_BrowseButton"] = "📁 Обзор…",
            ["Common_AllFilesFilter"] = "Все файлы (*.*)|*.*",
            ["Common_TextFileFilter"] = "Текстовый файл (*.txt)|*.txt",
            ["Common_BinFileFilter"] = "BIN файлы (*.bin)|*.bin|Все файлы (*.*)|*.*",
            ["Common_LogOpenButton"] = "Открыть",
            ["Common_LogSaveButton"] = "Сохранить",
            ["Common_LogClearButton"] = "Очистить",
            ["Common_LogTitle"] = "Журнал",
            ["Common_ProgressTitle"] = "Прогресс",
            ["Common_OpenFolderCheckbox"] = "Открыть папку с результатом",
            ["Common_SaveLogFailed"] = "Не удалось сохранить лог:\n{0}",
            ["Common_FileProgressLabel"] = "{0} — файл {1} из {2}",
            ["Common_OverwriteChoice"] = "Перезаписать",
            ["Common_CancelChoice"] = "Отмена",
            ["Common_DigitsOnly"] = "Разрешены только цифры",
            ["Common_DestinationFolderLabel"] = "Папка назначения",
            ["Common_NoFileSelected"] = "Файл не выбран",
            ["Common_NoFolderSelected"] = "Папка не выбрана",
            ["Common_CancelButton"] = "Отмена",
            ["Common_OkButton"] = "ОК",
            ["Update_GitHubRespondedError"] = "GitHub ответил: {0} {1}",
            ["Update_CheckFailedError"] = "Не удалось проверить обновления: {0}",

            // ===================== Размеры (SizeFormatHelper) =====================
            ["Size_GbFormat"] = "{0:F2} ГБ ({1:N0} байт)",
            ["Size_MbFormat"] = "{0:F2} МБ ({1:N0} байт)",

            // ===================== Ядро: исключения и журнал =====================
            ["Core_SourceFileNotFound"] = "Исходный файл не найден",
            ["Core_ChainBaseFileNotFound"] = "Базовый файл цепочки не найден",
            ["Core_CannotDetermineDrive"] = "Не удалось определить диск для пути: {0}",
            ["Log_Created"] = "Лог создан",
            ["Log_Cleared"] = "Лог очищен",
            ["Log_AppStarted"] = "Приложение запущено",
            ["Log_TimestampLabel"] = "Дата и время",
            ["Log_PartCreated"] = "Создан {0} (файл {1} из {2})",
            ["Log_PartFilled"] = "Файл {0} заполнен ({1:N0} байт)",
            ["Log_PartFinished"] = "Файл {0} завершён ({1:N0} байт)",
            ["Log_VerifyingHash"] = "Проверка SHA-256: повторное чтение всех частей подряд...",
            ["Log_HashMatches"] = "SHA-256 совпадает — байты не потеряны",
            ["Log_HashMismatchError"] = "ОШИБКА: SHA-256 НЕ совпадает! Проверьте результат.",
            ["Log_ChainFound"] = "Найдено частей в цепочке: {0} (всего {1:N0} байт)",
            ["Log_ReadingPart"] = "Читаю {0} (файл {1} из {2})",
            ["Log_MergeFinished"] = "Сборка завершена: {0} ({1:N0} байт)",

            // ===================== Оболочка/навигация/автообновление =====================
            ["Shell_NavConvert"] = "Конвертирование",
            ["Shell_NavMerge"] = "Сборка файла",
            ["Shell_NavVerify"] = "Проверка SHA-256",
            ["Shell_NavExtract"] = "Извлечение разделов",
            ["Shell_NavTerminal"] = "Терминал",
            ["Shell_NavSettings"] = "Настройки",
            ["Shell_NavAbout"] = "О программе",
            ["Shell_ToolsGroupHeader"] = "ИНСТРУМЕНТЫ",
            ["Shell_SystemGroupHeader"] = "СИСТЕМА",
            ["Shell_WindowTitle"] = "Tweak Firmware",
            ["Shell_TitleBarTitle"] = "Tweak Firmware",
            ["Shell_UpdateBanner"] = "Доступна новая версия {0}",
            ["Shell_UpdateDownloadButton"] = "Скачать",
            ["Shell_UpdateInstallButton"] = "Установить и перезапустить",
            ["Shell_UpdateReadyBanner"] = "Версия {0} загружена и готова к установке",
            ["Shell_UpdateWaitingForOperation"] = "Установка будет доступна после завершения операции",
            ["Shell_UpdateDownloadCancelledLog"] = "Загрузка обновления отменена",
            ["Shell_UpdateInstallerMissingMessage"] = "Скачанный установщик не найден — попробуйте скачать обновление заново.",
            ["Shell_LaterButton"] = "Позже",
            ["Shell_DownloadingUpdate"] = "Загрузка обновления... {0:F0}%",
            ["Shell_Installing"] = "Установка...",
            ["Shell_UpdateErrorTitle"] = "Ошибка обновления",
            ["Shell_UpdateErrorMessage"] = "Не удалось скачать или установить обновление:\n{0}",
            ["Shell_UpdateFoundLog"] = "Найдено обновление: версия {0} (текущая {1})",
            ["Shell_UpdateDownloadStartLog"] = "Начата загрузка обновления {0}: {1}",
            ["Shell_UpdateDownloadedLog"] = "Обновление скачано и готово к установке",
            ["Shell_UpdateErrorLog"] = "Ошибка автообновления: {0}",
            ["Shell_Placeholder_InDevelopment"] = "В разработке",

            // ===================== Конвертирование =====================
            ["Convert_Title"] = "Конвертирование",
            ["Convert_SourceFileLabel"] = "Исходный файл .bin",
            ["Convert_ProgrammerModelLabel"] = "Модель программатора",
            ["Convert_LimitLabel"] = "Лимит на один файл",
            ["Convert_GeneralInfoTitle"] = "Общая информация",
            ["Convert_ParametersTitle"] = "Параметры",
            ["Convert_VerifyHashCheckbox"] = "Проверить SHA-256",
            ["Convert_CheckDiskSpaceCheckbox"] = "Проверить свободное место на диске",
            ["Convert_OverallProgressLabel"] = "Конвертирование",
            ["Convert_CurrentFileProgressLabel"] = "Текущий файл",
            ["Convert_HashProgressLabel"] = "Алгоритм SHA-256",
            ["Convert_StartButton"] = "Начать",
            ["Convert_CustomPresetName"] = "Пользовательские настройки",
            ["Convert_ChooseOutputFolderTitle"] = "Выберите папку вывода",
            ["Convert_ShowAllFilesButton"] = "Показать все файлы",
            ["Convert_SourceSizeLine"] = "Размер исходного файла: {0}",
            ["Convert_ExpectedCountLine"] = "Ожидаемое количество файлов: {0}",
            ["Convert_InvalidLimitSuffix"] = " (введите корректный размер части, минимум 1024 байта)",
            ["Convert_TooManyFilesSuffix"] = " (слишком много для отображения по отдельности)",
            ["Convert_EachFileSizeHeader"] = "Размер каждого файла:",
            ["Convert_FileSizeLine"] = "Файл {0}: {1}",
            ["Convert_MoreFilesLine"] = "… и ещё {0} файл(ов)",
            ["Convert_CollapseList"] = "Свернуть список",
            ["Convert_ShowAllFilesCount"] = "Показать все {0} файлов",
            ["Convert_SelectSourceFirst"] = "Выберите существующий исходный файл.",
            ["Convert_SpecifyOutputFolder"] = "Укажите папку вывода.",
            ["Convert_InvalidPartSize"] = "Некорректный размер части.",
            ["Convert_ConflictTitle"] = "Файлы уже существуют",
            ["Convert_ConflictMessage"] = "В папке уже есть файлы с именем «{0}» (или его частей).",
            ["Convert_NewFolderNearby"] = "Новая папка",
            ["Convert_ConflictLog"] = "Обнаружен конфликт имён — используется новая папка: {0}",
            ["Convert_LowSpaceTitle"] = "Недостаточно места",
            ["Convert_LowSpaceMessage"] = "Размер исходного файла: {0}\nНеобходимо (с запасом 5%): {1}\nСвободно: {2}\nНе хватает: {3}",
            ["Convert_StartLog"] = "Начало конвертирования: {0} -> {1}\\{2} (макс. {3:N0} байт/файл)",
            ["Convert_FinishedLog"] = "Конвертирование завершено. Файлов: {0}, всего байт: {1:N0}",
            ["Convert_DoneTitle"] = "Готово",
            ["Convert_DoneVerifiedMessage"] = "Конвертирование завершено успешно.\nСоздано файлов: {0}\n\nSHA-256 совпадает — данные не повреждены.\n\n{1}",
            ["Convert_VerifyErrorTitle"] = "Ошибка проверки",
            ["Convert_VerifyErrorMessage"] = "ВНИМАНИЕ: контрольные суммы не совпадают!\n\nИсточник:\n{0}\n\nРезультат:\n{1}",
            ["Convert_DoneMessage"] = "Конвертирование завершено.\nСоздано файлов: {0}",
            ["Convert_OpenFolderFailedLog"] = "Не удалось открыть папку: {0}",
            ["Convert_CancelledLog"] = "Конвертирование отменено пользователем",
            ["Convert_CancelledTitle"] = "Отменено",
            ["Convert_CancelledMessage"] = "Конвертирование отменено.\nУдалено незавершённых файлов: {0}",
            ["Convert_ErrorLog"] = "ОШИБКА: {0}",
            ["Convert_DiskFullMessage"] = "На диске закончилось свободное место во время записи.\n\nОперация прервана, незавершённые файлы ({0}) удалены — освободите место и попробуйте снова.",
            ["Convert_ErrorMessage"] = "Ошибка при конвертировании:\n{0}\n\nНезавершённые файлы ({1}) удалены.",
            ["Common_DeletingIncompleteLog"] = "Удаление незавершённых файлов ({0})...",
            ["Common_DeletedLog"] = "Удалён: {0}",
            ["Common_DeleteFailedLog"] = "Не удалось удалить {0}: {1}",
            ["Convert_ResumedLog"] = "Операция возобновлена пользователем",
            ["Convert_PausedLog"] = "Операция приостановлена пользователем",

            // ===================== Сборка файла =====================
            ["Merge_Title"] = "Сборка файла",
            ["Merge_SourceFileFilter"] = "BIN и части (*.bin;*.part*)|*.bin;*.bin.part*|Все файлы (*.*)|*.*",
            ["Merge_AnyChainPartLabel"] = "Любая часть цепочки",
            ["Merge_ExpectedHashLabel"] = "Ожидаемый SHA-256",
            ["Merge_ExpectedHashTooltip"] = "Если известен хэш оригинального файла — вставьте сюда для сверки",
            ["Merge_ExpectedHashPlaceholder"] = "Необязательно — вставьте, если известен",
            ["Merge_ResultSizeLine"] = "Размер итогового файла: {0}",
            ["Merge_OverallProgressLabel"] = "Сборка",
            ["Merge_StartButton"] = "Начать",
            ["Merge_ChainFoundInfo"] = "Найдено частей: {0} ({1}). Первая: {2}",
            ["Merge_ChainResolveError"] = "Не удалось определить цепочку: {0}",
            ["Merge_SelectSourceFirst"] = "Выберите файл из цепочки частей.",
            ["Merge_SpecifyOutputFile"] = "Укажите файл результата.",
            ["Merge_FileExistsTitle"] = "Файл уже существует",
            ["Merge_FileExistsMessage"] = "Файл «{0}» уже существует.",
            ["Merge_NewNameNearby"] = "Новое имя",
            ["Merge_ConflictLog"] = "Обнаружен конфликт имени — используется новый файл: {0}",
            ["Merge_ChainCheckErrorMessage"] = "Не удалось проверить цепочку частей:\n{0}",
            ["Merge_LowSpaceMessage"] = "Размер собираемых данных: {0}\nНеобходимо (с запасом 5%): {1}\nСвободно: {2}\nНе хватает: {3}",
            ["Merge_StartLog"] = "Начало сборки: {0} -> {1}",
            ["Merge_FinishedLog"] = "Сборка завершена. Частей: {0}, байт: {1:N0}",
            ["Merge_ResultHashLog"] = "SHA-256 результата: {0}",
            ["Merge_HashMatchLog"] = "Сверка с указанным хэшем: совпадает ✓",
            ["Merge_HashMismatchLog"] = "Сверка с указанным хэшем: НЕ совпадает!",
            ["Merge_ResultTitle"] = "Результат сборки",
            ["Merge_ResultMatchMessage"] = "Сборка завершена.\nSHA-256 совпадает с указанным.\n\n{0}",
            ["Merge_ResultMismatchMessage"] = "ВНИМАНИЕ: SHA-256 НЕ совпадает!\n\nОжидался:\n{0}\n\nПолучен:\n{1}",
            ["Merge_DoneMessage"] = "Сборка завершена.\nЧастей: {0}\nРазмер: {1:N0} байт\n\nSHA-256:\n{2}",
            ["Merge_CancelledLog"] = "Сборка отменена пользователем",
            ["Merge_CancelledMessage"] = "Сборка отменена.\nНезавершённый файл результата удалён.",
            ["Merge_DiskFullMessage"] = "На диске закончилось свободное место во время записи.\n\nОперация прервана, незавершённый файл результата удалён — освободите место и попробуйте снова.",
            ["Merge_ErrorMessage"] = "Ошибка при сборке:\n{0}\n\nНезавершённый файл результата удалён.",
            ["Merge_ResumedLog"] = "Операция возобновлена пользователем",
            ["Merge_PausedLog"] = "Операция приостановлена пользователем",

            // ===================== Проверка SHA-256 =====================
            ["Verify_Title"] = "Проверка SHA-256",
            ["Verify_FileALabel"] = "Файл А",
            ["Verify_FileBLabel"] = "Файл Б",
            ["Verify_CompareProgressLabel"] = "Сравнение",
            ["Verify_CompareButton"] = "Начать",
            ["Verify_SelectBothFiles"] = "Выберите оба файла.",
            ["Verify_CompareLog"] = "Сравнение хэшей: {0}  vs  {1}",
            ["Verify_FileALabelProgress"] = "Файл А — {0}",
            ["Verify_FileBLabelProgress"] = "Файл Б — {0}",
            ["Verify_HashesMatchLog"] = "Хэши совпадают",
            ["Verify_HashesMismatchLog"] = "Хэши НЕ совпадают",
            ["Verify_ResultTitle"] = "Результат",
            ["Verify_HashALine"] = "Хэш файла А:",
            ["Verify_HashBLine"] = "Хэш файла Б:",
            ["Verify_NoResultYet"] = "Сравнение ещё не выполнялось",
            ["Verify_MatchResult"] = "Хэши совпадают — данные идентичны",
            ["Verify_MismatchResult"] = "Хэши НЕ совпадают — файлы различаются",
            ["Verify_HashErrorMessage"] = "Ошибка при вычислении хэша:\n{0}",

            // ===================== Настройки =====================
            ["Settings_Title"] = "Настройки",
            ["Settings_ThemeTitle"] = "Тема оформления",
            ["Settings_ThemeLight"] = "Светлая",
            ["Settings_ThemeDark"] = "Тёмная",
            ["Settings_ThemeSystem"] = "Как в системе",
            ["Settings_LanguageTitle"] = "Язык",
            ["Settings_LanguageRu"] = "Русский",
            ["Settings_LanguageEn"] = "English",
            ["Settings_UseDefaultPathCheckbox"] = "Путь по умолчанию",
            ["Settings_ChooseConvertFolderTitle"] = "Папка по умолчанию для конвертирования",
            ["Settings_ChooseMergeFolderTitle"] = "Папка по умолчанию для сборки файла",
            ["Settings_ConvertFolderTitle"] = "Папка для конвертирования",
            ["Settings_MergeFolderTitle"] = "Папка для сборки файла",
            ["Settings_ClearCacheTitle"] = "Очистить кеш",
            ["Settings_ClearCacheDescription"] = "Удаляет временные файлы и журнал приложения.",
            ["Settings_CacheClearedTitle"] = "Готово",
            ["Settings_CacheClearedMessage"] = "Временные файлы и журналы очищены.",

            // ===================== О программе =====================
            ["About_Title"] = "О программе",
            ["About_UpdatesTitle"] = "Обновления",
            ["About_CheckUpdatesButton"] = "Проверить обновления",
            ["About_Checking"] = "Проверка...",
            ["About_UpdateAvailable"] = "Доступна новая версия: {0} (см. уведомление сверху)",
            ["About_UpToDate"] = "У вас последняя версия.",
            ["About_CheckUpdatesTitle"] = "Проверка обновлений",
            ["About_DevelopmentTitle"] = "Разработка",
            ["About_DevelopmentText"] = "Alxmak и несколько чат-ботов.",
            ["About_PersonalUseText"] = "Программа создавалась для использования в личных целях.",
            ["About_SourcesTitle"] = "Источники информации",
            ["About_VersionText"] = "Версия {0}",

            // ===================== Обратная связь =====================
            ["Feedback_Title"] = "Обратная связь",
            ["Feedback_Intro"] = "Пожелания, сообщения об ошибках и просто желание связаться — пишите на адрес:",
            ["Feedback_NameLabel"] = "Имя или логин",
            ["Feedback_NamePlaceholder"] = "Необязательно",
            ["Feedback_ReplyToLabel"] = "Почта для ответа",
            ["Feedback_ReplyToPlaceholder"] = "Необязательно, но без неё не смогу ответить",
            ["Feedback_MessageLabel"] = "Сообщение",
            ["Feedback_MessagePlaceholder"] = "Что случилось или что хотелось бы добавить",
            ["Feedback_SendButton"] = "Написать",
            ["Feedback_CopyButton"] = "Скопировать письмо",
            ["Feedback_Hint"] = "Кнопка открывает ваш почтовый клиент с готовым письмом — отправка происходит из него, программа ничего никуда не передаёт сама.",
            ["Feedback_OpenedStatus"] = "Письмо открыто в почтовом клиенте.",
            ["Feedback_OpenedPasteHint"] = "Письмо длинное и в ссылку не поместилось: текст скопирован в буфер обмена, вставьте его в открывшееся письмо (Ctrl+V).",
            ["Feedback_CopiedStatus"] = "Текст письма скопирован в буфер обмена.",
            ["Feedback_CopyFailedStatus"] = "Не удалось скопировать: буфером обмена занято другое приложение, попробуйте ещё раз.",
            ["Feedback_NoMailClientCopied"] = "Не удалось открыть почтовый клиент — похоже, он не назначен в системе. Текст письма скопирован в буфер обмена, отправьте его вручную на {0}.",
            ["Feedback_NoMailClient"] = "Не удалось открыть почтовый клиент — похоже, он не назначен в системе. Напишите, пожалуйста, вручную на {0}.",
            ["Feedback_MailSubject"] = "Tweak Firmware {0} — обратная связь",
            ["Feedback_BodyNameLine"] = "Имя: {0}",
            ["Feedback_BodyReplyToLine"] = "Обратный адрес: {0}",
            ["Feedback_BodyVersionLine"] = "Версия: {0}",
            ["Feedback_BodyOsLine"] = "Система: {0}",
            ["Feedback_MailClientFailedLog"] = "Обратная связь: не удалось открыть почтовый клиент ({0}).",
            ["Feedback_ClipboardFailedLog"] = "Обратная связь: не удалось записать в буфер обмена ({0}).",

            // ===================== Заглушки разделов в разработке =====================
            ["Placeholder_ExtractTitle"] = "Извлечение разделов",
            ["Placeholder_TerminalTitle"] = "Терминал",
        };

        private static readonly Dictionary<string, string> En = new()
        {
            // ===================== Common =====================
            ["Common_Error"] = "Error",
            ["Common_PauseButton"] = "Pause",
            ["Common_ResumeButton"] = "Resume",
            ["Common_FileNotFoundMessage"] = "File not found.",
            ["Common_BrowseButton"] = "📁 Browse…",
            ["Common_AllFilesFilter"] = "All files (*.*)|*.*",
            ["Common_TextFileFilter"] = "Text file (*.txt)|*.txt",
            ["Common_BinFileFilter"] = "BIN files (*.bin)|*.bin|All files (*.*)|*.*",
            ["Common_LogOpenButton"] = "Open",
            ["Common_LogSaveButton"] = "Save",
            ["Common_LogClearButton"] = "Clear",
            ["Common_LogTitle"] = "Log",
            ["Common_ProgressTitle"] = "Progress",
            ["Common_OpenFolderCheckbox"] = "Open the result folder",
            ["Common_SaveLogFailed"] = "Failed to save the log:\n{0}",
            ["Common_FileProgressLabel"] = "{0} — file {1} of {2}",
            ["Common_OverwriteChoice"] = "Overwrite",
            ["Common_CancelChoice"] = "Cancel",
            ["Common_DigitsOnly"] = "Digits only are allowed",
            ["Common_DestinationFolderLabel"] = "Destination folder",
            ["Common_NoFileSelected"] = "No file selected",
            ["Common_NoFolderSelected"] = "No folder selected",
            ["Common_CancelButton"] = "Cancel",
            ["Common_OkButton"] = "OK",
            ["Update_GitHubRespondedError"] = "GitHub responded: {0} {1}",
            ["Update_CheckFailedError"] = "Failed to check for updates: {0}",

            // ===================== Sizes (SizeFormatHelper) =====================
            ["Size_GbFormat"] = "{0:F2} GB ({1:N0} bytes)",
            ["Size_MbFormat"] = "{0:F2} MB ({1:N0} bytes)",

            // ===================== Core: exceptions and log =====================
            ["Core_SourceFileNotFound"] = "Source file not found",
            ["Core_ChainBaseFileNotFound"] = "Base file of the chain not found",
            ["Core_CannotDetermineDrive"] = "Could not determine the drive for path: {0}",
            ["Log_Created"] = "Log created",
            ["Log_Cleared"] = "Log cleared",
            ["Log_TimestampLabel"] = "Date and time",
            ["Log_AppStarted"] = "Application started",
            ["Log_PartCreated"] = "Created {0} (file {1} of {2})",
            ["Log_PartFilled"] = "File {0} filled ({1:N0} bytes)",
            ["Log_PartFinished"] = "File {0} finished ({1:N0} bytes)",
            ["Log_VerifyingHash"] = "Verifying SHA-256: re-reading all parts in sequence...",
            ["Log_HashMatches"] = "SHA-256 matches — no bytes lost",
            ["Log_HashMismatchError"] = "ERROR: SHA-256 does NOT match! Check the result.",
            ["Log_ChainFound"] = "Found parts in the chain: {0} (total {1:N0} bytes)",
            ["Log_ReadingPart"] = "Reading {0} (file {1} of {2})",
            ["Log_MergeFinished"] = "Merge finished: {0} ({1:N0} bytes)",

            // ===================== Shell/navigation/auto-update =====================
            ["Shell_NavConvert"] = "Convert",
            ["Shell_NavMerge"] = "Merge file",
            ["Shell_NavVerify"] = "Verify SHA-256",
            ["Shell_NavExtract"] = "Extract partitions",
            ["Shell_NavTerminal"] = "Terminal",
            ["Shell_NavSettings"] = "Settings",
            ["Shell_NavAbout"] = "About",
            ["Shell_ToolsGroupHeader"] = "TOOLS",
            ["Shell_SystemGroupHeader"] = "SYSTEM",
            ["Shell_WindowTitle"] = "Tweak Firmware",
            ["Shell_TitleBarTitle"] = "Tweak Firmware",
            ["Shell_UpdateBanner"] = "Version {0} is available",
            ["Shell_UpdateDownloadButton"] = "Download",
            ["Shell_UpdateInstallButton"] = "Install and restart",
            ["Shell_UpdateReadyBanner"] = "Version {0} is downloaded and ready to install",
            ["Shell_UpdateWaitingForOperation"] = "Installing will be available once the operation finishes",
            ["Shell_UpdateDownloadCancelledLog"] = "Update download cancelled",
            ["Shell_UpdateInstallerMissingMessage"] = "The downloaded installer is missing — try downloading the update again.",
            ["Shell_LaterButton"] = "Later",
            ["Shell_DownloadingUpdate"] = "Downloading update... {0:F0}%",
            ["Shell_Installing"] = "Installing...",
            ["Shell_UpdateErrorTitle"] = "Update error",
            ["Shell_UpdateErrorMessage"] = "Failed to download or install the update:\n{0}",
            ["Shell_UpdateFoundLog"] = "Update found: version {0} (current {1})",
            ["Shell_UpdateDownloadStartLog"] = "Started downloading update {0}: {1}",
            ["Shell_UpdateDownloadedLog"] = "Update downloaded and ready to install",
            ["Shell_UpdateErrorLog"] = "Auto-update error: {0}",
            ["Shell_Placeholder_InDevelopment"] = "Under development",

            // ===================== Convert =====================
            ["Convert_Title"] = "Convert",
            ["Convert_SourceFileLabel"] = "Source .bin file",
            ["Convert_ProgrammerModelLabel"] = "Programmer model",
            ["Convert_LimitLabel"] = "Limit per file",
            ["Convert_GeneralInfoTitle"] = "General info",
            ["Convert_ParametersTitle"] = "Parameters",
            ["Convert_VerifyHashCheckbox"] = "Verify SHA-256",
            ["Convert_CheckDiskSpaceCheckbox"] = "Check free space on the disk",
            ["Convert_OverallProgressLabel"] = "Conversion",
            ["Convert_CurrentFileProgressLabel"] = "Current file",
            ["Convert_HashProgressLabel"] = "SHA-256 algorithm",
            ["Convert_StartButton"] = "Start",
            ["Convert_CustomPresetName"] = "Custom settings",
            ["Convert_ChooseOutputFolderTitle"] = "Choose the output folder",
            ["Convert_ShowAllFilesButton"] = "Show all files",
            ["Convert_SourceSizeLine"] = "Source file size: {0}",
            ["Convert_ExpectedCountLine"] = "Expected file count: {0}",
            ["Convert_InvalidLimitSuffix"] = " (enter a valid part size, minimum 1024 bytes)",
            ["Convert_TooManyFilesSuffix"] = " (too many to list individually)",
            ["Convert_EachFileSizeHeader"] = "Size of each file:",
            ["Convert_FileSizeLine"] = "File {0}: {1}",
            ["Convert_MoreFilesLine"] = "… and {0} more file(s)",
            ["Convert_CollapseList"] = "Collapse the list",
            ["Convert_ShowAllFilesCount"] = "Show all {0} files",
            ["Convert_SelectSourceFirst"] = "Select an existing source file.",
            ["Convert_SpecifyOutputFolder"] = "Specify the output folder.",
            ["Convert_InvalidPartSize"] = "Invalid part size.",
            ["Convert_ConflictTitle"] = "Files already exist",
            ["Convert_ConflictMessage"] = "The folder already contains files named \"{0}\" (or its parts).",
            ["Convert_NewFolderNearby"] = "New folder",
            ["Convert_ConflictLog"] = "Name conflict detected — using a new folder: {0}",
            ["Convert_LowSpaceTitle"] = "Not enough space",
            ["Convert_LowSpaceMessage"] = "Source file size: {0}\nRequired (with 5% margin): {1}\nAvailable: {2}\nMissing: {3}",
            ["Convert_StartLog"] = "Starting conversion: {0} -> {1}\\{2} (max {3:N0} bytes/file)",
            ["Convert_FinishedLog"] = "Conversion finished. Files: {0}, total bytes: {1:N0}",
            ["Convert_DoneTitle"] = "Done",
            ["Convert_DoneVerifiedMessage"] = "Conversion completed successfully.\nFiles created: {0}\n\nSHA-256 matches — data is intact.\n\n{1}",
            ["Convert_VerifyErrorTitle"] = "Verification error",
            ["Convert_VerifyErrorMessage"] = "WARNING: checksums do not match!\n\nSource:\n{0}\n\nResult:\n{1}",
            ["Convert_DoneMessage"] = "Conversion completed.\nFiles created: {0}",
            ["Convert_OpenFolderFailedLog"] = "Failed to open the folder: {0}",
            ["Convert_CancelledLog"] = "Conversion cancelled by the user",
            ["Convert_CancelledTitle"] = "Cancelled",
            ["Convert_CancelledMessage"] = "Conversion cancelled.\nIncomplete files deleted: {0}",
            ["Convert_ErrorLog"] = "ERROR: {0}",
            ["Convert_DiskFullMessage"] = "The disk ran out of space while writing.\n\nThe operation was interrupted, incomplete files ({0}) were deleted — free up space and try again.",
            ["Convert_ErrorMessage"] = "Error during conversion:\n{0}\n\nIncomplete files ({1}) deleted.",
            ["Common_DeletingIncompleteLog"] = "Deleting incomplete files ({0})...",
            ["Common_DeletedLog"] = "Deleted: {0}",
            ["Common_DeleteFailedLog"] = "Failed to delete {0}: {1}",
            ["Convert_ResumedLog"] = "Operation resumed by the user",
            ["Convert_PausedLog"] = "Operation paused by the user",

            // ===================== Merge =====================
            ["Merge_Title"] = "Merge file",
            ["Merge_SourceFileFilter"] = "BIN and parts (*.bin;*.part*)|*.bin;*.bin.part*|All files (*.*)|*.*",
            ["Merge_AnyChainPartLabel"] = "Any part of the chain",
            ["Merge_ExpectedHashLabel"] = "Expected SHA-256",
            ["Merge_ExpectedHashTooltip"] = "If you know the original file's hash, paste it here to verify",
            ["Merge_ExpectedHashPlaceholder"] = "Optional — paste it if you know it",
            ["Merge_ResultSizeLine"] = "Final file size: {0}",
            ["Merge_OverallProgressLabel"] = "Merge",
            ["Merge_StartButton"] = "Start",
            ["Merge_ChainFoundInfo"] = "Parts found: {0} ({1}). First: {2}",
            ["Merge_ChainResolveError"] = "Could not determine the chain: {0}",
            ["Merge_SelectSourceFirst"] = "Select a file from the part chain.",
            ["Merge_SpecifyOutputFile"] = "Specify the result file.",
            ["Merge_FileExistsTitle"] = "File already exists",
            ["Merge_FileExistsMessage"] = "File \"{0}\" already exists.",
            ["Merge_NewNameNearby"] = "New name",
            ["Merge_ConflictLog"] = "Name conflict detected — using a new file: {0}",
            ["Merge_ChainCheckErrorMessage"] = "Failed to check the part chain:\n{0}",
            ["Merge_LowSpaceMessage"] = "Size of the data being merged: {0}\nRequired (with 5% margin): {1}\nAvailable: {2}\nMissing: {3}",
            ["Merge_StartLog"] = "Starting merge: {0} -> {1}",
            ["Merge_FinishedLog"] = "Merge finished. Parts: {0}, bytes: {1:N0}",
            ["Merge_ResultHashLog"] = "Result SHA-256: {0}",
            ["Merge_HashMatchLog"] = "Comparison with the specified hash: matches ✓",
            ["Merge_HashMismatchLog"] = "Comparison with the specified hash: does NOT match!",
            ["Merge_ResultTitle"] = "Merge result",
            ["Merge_ResultMatchMessage"] = "Merge completed.\nSHA-256 matches the specified one.\n\n{0}",
            ["Merge_ResultMismatchMessage"] = "WARNING: SHA-256 does NOT match!\n\nExpected:\n{0}\n\nGot:\n{1}",
            ["Merge_DoneMessage"] = "Merge completed.\nParts: {0}\nSize: {1:N0} bytes\n\nSHA-256:\n{2}",
            ["Merge_CancelledLog"] = "Merge cancelled by the user",
            ["Merge_CancelledMessage"] = "Merge cancelled.\nThe incomplete result file was deleted.",
            ["Merge_DiskFullMessage"] = "The disk ran out of space while writing.\n\nThe operation was interrupted, the incomplete result file was deleted — free up space and try again.",
            ["Merge_ErrorMessage"] = "Error during merge:\n{0}\n\nThe incomplete result file was deleted.",
            ["Merge_ResumedLog"] = "Operation resumed by the user",
            ["Merge_PausedLog"] = "Operation paused by the user",

            // ===================== Verify SHA-256 =====================
            ["Verify_Title"] = "Verify SHA-256",
            ["Verify_FileALabel"] = "File A",
            ["Verify_FileBLabel"] = "File B",
            ["Verify_CompareProgressLabel"] = "Comparison",
            ["Verify_CompareButton"] = "Start",
            ["Verify_SelectBothFiles"] = "Select both files.",
            ["Verify_CompareLog"] = "Comparing hashes: {0}  vs  {1}",
            ["Verify_FileALabelProgress"] = "File A — {0}",
            ["Verify_FileBLabelProgress"] = "File B — {0}",
            ["Verify_HashesMatchLog"] = "Hashes match",
            ["Verify_HashesMismatchLog"] = "Hashes do NOT match",
            ["Verify_ResultTitle"] = "Result",
            ["Verify_HashALine"] = "File A hash:",
            ["Verify_HashBLine"] = "File B hash:",
            ["Verify_NoResultYet"] = "No comparison has been run yet",
            ["Verify_MatchResult"] = "Hashes match — data is identical",
            ["Verify_MismatchResult"] = "Hashes do NOT match — files differ",
            ["Verify_HashErrorMessage"] = "Error computing the hash:\n{0}",

            // ===================== Settings =====================
            ["Settings_Title"] = "Settings",
            ["Settings_ThemeTitle"] = "Theme",
            ["Settings_ThemeLight"] = "Light",
            ["Settings_ThemeDark"] = "Dark",
            ["Settings_ThemeSystem"] = "Same as system",
            ["Settings_LanguageTitle"] = "Language",
            ["Settings_LanguageRu"] = "Russian",
            ["Settings_LanguageEn"] = "English",
            ["Settings_UseDefaultPathCheckbox"] = "Default path",
            ["Settings_ChooseConvertFolderTitle"] = "Default folder for conversion",
            ["Settings_ChooseMergeFolderTitle"] = "Default folder for merging",
            ["Settings_ConvertFolderTitle"] = "Convert folder",
            ["Settings_MergeFolderTitle"] = "Merge folder",
            ["Settings_ClearCacheTitle"] = "Clear cache",
            ["Settings_ClearCacheDescription"] = "Removes temporary files and the application log.",
            ["Settings_CacheClearedTitle"] = "Done",
            ["Settings_CacheClearedMessage"] = "Temporary files and logs have been cleared.",

            // ===================== About =====================
            ["About_Title"] = "About",
            ["About_UpdatesTitle"] = "Updates",
            ["About_CheckUpdatesButton"] = "Check for updates",
            ["About_Checking"] = "Checking...",
            ["About_UpdateAvailable"] = "A new version is available: {0} (see the notice above)",
            ["About_UpToDate"] = "You have the latest version.",
            ["About_CheckUpdatesTitle"] = "Check for updates",
            ["About_DevelopmentTitle"] = "Development",
            ["About_DevelopmentText"] = "Alxmak and a few chatbots.",
            ["About_PersonalUseText"] = "This program was created for personal use.",
            ["About_SourcesTitle"] = "Sources",
            ["About_VersionText"] = "Version {0}",

            // ===================== Feedback =====================
            ["Feedback_Title"] = "Feedback",
            ["Feedback_Intro"] = "Suggestions, bug reports or just getting in touch — write to:",
            ["Feedback_NameLabel"] = "Name or nickname",
            ["Feedback_NamePlaceholder"] = "Optional",
            ["Feedback_ReplyToLabel"] = "Email for a reply",
            ["Feedback_ReplyToPlaceholder"] = "Optional, but without it I cannot reply",
            ["Feedback_MessageLabel"] = "Message",
            ["Feedback_MessagePlaceholder"] = "What happened, or what you would like added",
            ["Feedback_SendButton"] = "Write",
            ["Feedback_CopyButton"] = "Copy the letter",
            ["Feedback_Hint"] = "The button opens your mail client with the letter ready — sending happens there, the program does not transmit anything on its own.",
            ["Feedback_OpenedStatus"] = "The letter is open in your mail client.",
            ["Feedback_OpenedPasteHint"] = "The letter was too long for the link: its text has been copied to the clipboard, paste it into the message that opened (Ctrl+V).",
            ["Feedback_CopiedStatus"] = "The letter has been copied to the clipboard.",
            ["Feedback_CopyFailedStatus"] = "Could not copy: another application is holding the clipboard, please try again.",
            ["Feedback_NoMailClientCopied"] = "Could not open a mail client — it seems none is set up in the system. The letter has been copied to the clipboard, please send it manually to {0}.",
            ["Feedback_NoMailClient"] = "Could not open a mail client — it seems none is set up in the system. Please write manually to {0}.",
            ["Feedback_MailSubject"] = "Tweak Firmware {0} — feedback",
            ["Feedback_BodyNameLine"] = "Name: {0}",
            ["Feedback_BodyReplyToLine"] = "Reply to: {0}",
            ["Feedback_BodyVersionLine"] = "Version: {0}",
            ["Feedback_BodyOsLine"] = "System: {0}",
            ["Feedback_MailClientFailedLog"] = "Feedback: could not open a mail client ({0}).",
            ["Feedback_ClipboardFailedLog"] = "Feedback: could not write to the clipboard ({0}).",

            // ===================== In-development placeholders =====================
            ["Placeholder_ExtractTitle"] = "Extract partitions",
            ["Placeholder_TerminalTitle"] = "Terminal",
        };
    }
}
